'use strict';
const { io } = require('socket.io-client');
const DominoesEngine = require('./dominoes-engine');
const SkipBoEngine = require('./skipbo-engine');
const emit=(socket,event,data={})=>new Promise(resolve=>socket.emit(event,data,result=>resolve(result||{ok:false})));
function startComputerPlayer({url,roomCode,secret,onReady}){
 const socket=io(url,{transports:['websocket'],reconnection:true});let playerId=null,busy=false;const seen=new Map(),turnDelay=process.env.NODE_ENV==='test'?5:650;
 async function once(key,game,action){if(!game||game.status!=='playing'||game.turnPlayerId!==playerId||busy)return;const marker=`${game.sequence}:${game.phase||''}:${game.pendingDraw||0}:${game.movesRemaining||0}:${game.turnPlayerId||''}`;const lastMarker=seen.get(key);if(lastMarker===marker)return;seen.set(key,marker);busy=true;try{await new Promise(r=>setTimeout(r,turnDelay));busy=false;await action()}finally{busy=false}}
 socket.on('connect',()=>socket.emit('authenticate-computer',{roomCode,secret},result=>{if(!result?.ok)return socket.disconnect();playerId=result.playerId;onReady?.(result)}));
 socket.on('ducks-race-state',({game})=>once('duck',game,()=>emit(socket,'ducks-race-roll')));
 socket.on('monopoly-state',({game})=>{if(!game||busy)return;if(game.pendingTrade?.toId===playerId)return setTimeout(()=>emit(socket,'monopoly-trade-response',{accept:false}),turnDelay);if(game.pendingPurchase?.playerId===playerId)return setTimeout(()=>emit(socket,'monopoly-purchase-response',{accept:true}),turnDelay);return once('monopoly',game,()=>emit(socket,'monopoly-roll'))});
 socket.on('life-state',({game})=>once('life',game,()=>game.pendingChoice?.playerId===playerId?emit(socket,'life-choose',{choice:0}):emit(socket,'life-spin')));
 socket.on('derby-state',({game})=>once('derby',game,async()=>{if(!game.myHand.length)return emit(socket,'derby-draw');const targetId=game.players.find(p=>p.id!==playerId)?.id;for(let cardIndex=0;cardIndex<game.myHand.length;cardIndex+=1){const result=await emit(socket,'derby-play',{cardIndex,targetId});if(result.ok)return result}const ended=await emit(socket,'derby-end-turn');return ended.ok?ended:emit(socket,'derby-draw')}));
 socket.on('domino-state',({game})=>once('domino',game,async()=>{for(const tile of game.myHand)for(const end of ['left','right'])for(const flipped of [false,true]){try{DominoesEngine.placeTile(game.board,tile,end,flipped)}catch{continue}return emit(socket,'domino-play',{tileId:tile.id,end,flipped})}return emit(socket,'domino-draw')}));
 socket.on('skipbo-state',({game})=>once('skipbo',game,async()=>{const sources=[];if(game.myStockTop)sources.push({source:'stock',sourceIndex:0,card:game.myStockTop});game.myHand.forEach((card,index)=>sources.push({source:'hand',sourceIndex:index,card}));game.myDiscards.forEach((pile,index)=>{if(pile.length)sources.push({source:'discard',sourceIndex:index,card:pile.at(-1)})});for(const source of sources)for(let targetIndex=0;targetIndex<4;targetIndex+=1)if(SkipBoEngine.canBuild(source.card,game.buildingPiles[targetIndex]))return emit(socket,'skipbo-play',{source:source.source,sourceIndex:source.sourceIndex,targetType:'building',targetIndex});if(game.myHand.length)return emit(socket,'skipbo-play',{source:'hand',sourceIndex:0,targetType:'discard',targetIndex:0})}));
 socket.on('mall-state',({game})=>once('mall',game,async()=>{if(game.phase==='director')return emit(socket,'mall-director');if(game.phase==='action')return emit(socket,'mall-action');for(const direction of ['ArrowRight','ArrowDown','ArrowLeft','ArrowUp']){const result=await emit(socket,'mall-move',{direction});if(result.ok)return result}return emit(socket,'mall-action')}));
 socket.on('uno-state',({game})=>once('uno',game,async()=>{const attempts=[];if(game.variant==='Uno Dos'){for(let centerIndex=0;centerIndex<game.centerRow.length;centerIndex+=1)for(let first=0;first<game.myHand.length;first+=1){attempts.push({indexes:[first],centerIndex,color:'Red'});for(let second=first+1;second<game.myHand.length;second+=1)attempts.push({indexes:[first,second],centerIndex,color:'Red'})}}else game.myHand.forEach((_card,index)=>attempts.push({indexes:[index],color:'Red',centerIndex:0}));for(const attempt of attempts){const result=await emit(socket,'uno-play',attempt);if(result.ok)return result}return emit(socket,'uno-draw')}));
 return socket;
}
module.exports={startComputerPlayer};
