'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, 'ducks-race.html'), 'utf8');
const source = fs.readFileSync(path.join(__dirname, 'ducks-race.js'), 'utf8');
const skipBo = fs.readFileSync(path.join(__dirname, 'skipbo.js'), 'utf8');
const horseRace = fs.readFileSync(path.join(__dirname, 'horserace.js'), 'utf8');
const horseEngine = fs.readFileSync(path.join(__dirname, 'horserace-engine.js'), 'utf8');
const dominoes = fs.readFileSync(path.join(__dirname, 'dominoes.js'), 'utf8');
const uno = fs.readFileSync(path.join(__dirname, 'uno.js'), 'utf8');
const server = fs.readFileSync(path.join(__dirname, 'server.js'), 'utf8');
const audioSource = fs.readFileSync(path.join(__dirname, 'audio.js'), 'utf8');
const skipBoHtml = fs.readFileSync(path.join(__dirname, 'skipbo.html'), 'utf8');
const horseHtml = fs.readFileSync(path.join(__dirname, 'horserace.html'), 'utf8');

assert.match(html, /id="cards"[^>]*role="listbox"[^>]*aria-label="Your cards"/, 'The Duck Race hand must be exposed as a named listbox.');
assert(source.includes("item.setAttribute('role', 'option')"), 'Each Duck Race card must be exposed as an option.');
assert(source.includes('item.tabIndex = index === selectedCardIndex ? 0 : -1'), 'Only the selected card should be in the tab order.');
assert(source.includes("item.setAttribute('aria-selected', String(index === selectedCardIndex))"), 'The selected card must be conveyed to screen readers.');
assert(source.includes("if (event.key === 'ArrowUp' || event.key === 'ArrowDown')") && source.includes('else cycleCard(direction)'), 'Up and Down must cycle through the hand.');
assert(html.includes("role=\"listbox\" aria-label=\"Card targets\"") && source.includes("item.setAttribute('aria-selected', String(index === selectedTargetIndex))"), 'Duck Race player targets must expose selection to screen readers.');
assert(skipBo.includes('li.tabIndex = selection.source === \'hand\'') && skipBo.includes('el.hand.children[index]?.focus()'), 'Skip-Bo arrows must move screen-reader focus through the hand.');
assert(horseRace.includes("b.setAttribute('aria-label',`${cardText(name)} Card ${index+1} of ${game.myHand.length}.") && horseRace.includes("b.setAttribute('aria-disabled',String(!cardActive))"), 'Horse Race cards must stay readable outside the player turn and report when the turn card was already used.');
assert(dominoes.includes("button.setAttribute('aria-label',`${tileText(shown)}. Tile ${index+1} of ${game.myHand.length}. Press Enter to play.`)") && dominoes.includes("button.setAttribute('aria-disabled',String(!active))"), 'Domino tiles must stay readable outside the player turn.');
assert(uno.includes("li.setAttribute('role','option')") && uno.includes('li.tabIndex=index===selected?0:-1'), 'UNO and DOS cards must expose focused listbox options.');
assert(source.includes("item.addEventListener('click', () => { selectedTargetIndex = index; activateSelectedTarget(); })"), 'Duck Race targets must activate by click in visual mode.');
assert(skipBoHtml.includes('id="target-options"') && skipBo.includes("button.className = 'target-option'") && skipBo.includes("button.addEventListener('click', () => play(target.type, target.index))"), 'Skip-Bo must expose clickable and keyboard-focusable target choices.');
assert(skipBo.includes("li.addEventListener('click', () => select('hand', index))") && skipBo.includes("item.addEventListener('keydown', event =>"), 'Skip-Bo cards and private piles must be selectable by mouse and keyboard.');
assert(horseRace.includes("el.target.addEventListener('keydown',event=>") && horseRace.includes('el.confirmTarget.click()'), 'Horse Race opponent choices must submit with Enter.');
assert(dominoes.includes("button.addEventListener('click',playSelected)") && dominoes.includes('function playSelected()'), 'Domino tiles must play with Enter or click.');
assert(dominoes.includes("['arrowup','arrowdown','arrowleft','arrowright'].includes(key)") && dominoes.includes("if(key==='f'&&game?.myHand.length)"), 'Dominoes must use Up and Down to choose tiles, Enter to play, and F to flip.');
assert(source.includes("if (elements.cards.contains(document.activeElement))") && source.includes("document.activeElement.closest('[data-card-index]')"), 'Duck Race Enter must activate a focused card instead of rolling.');
assert(source.includes("rollItem.dataset.handAction = 'roll'") && source.includes("'Roll the Dice. Press Enter to roll.'") && source.includes('const handCount = me?.hand.length || 0'), 'Duck Race arrows must include Roll the Dice in the hand choices.');
assert(horseRace.includes('selected=-1') && horseRace.includes("roll.dataset.handAction='roll'") && horseRace.includes("if(selected===-1)") && horseRace.includes('const count=game.myHand.length+1'), 'Horse Race must default to and arrow through Roll the Dice with every hand card.');
assert(html.includes('Use Up or Down to choose Roll the Dice or a card') && fs.readFileSync(path.join(__dirname, 'horserace.html'), 'utf8').includes('Use Up or Down to choose Roll the Dice or a card'), 'Both dice-race hands must explain the combined roll-and-card list.');
assert(horseRace.includes("b.addEventListener('keydown',event=>") && horseRace.includes('event.stopPropagation();selected=index;playSelected()'), 'Horse Race Enter must activate the focused card without reaching global shortcuts.');
assert(dominoes.includes("button.addEventListener('keydown',event=>") && dominoes.includes('event.stopPropagation();selected=index;playSelected()'), 'Domino Enter must activate the focused tile without reaching global shortcuts.');
assert(uno.includes("li.addEventListener('keydown',event=>") && uno.includes('event.stopPropagation();selected=index;playOrDraw()'), 'UNO and DOS Enter must activate the focused card without reaching global shortcuts.');
assert(skipBo.includes('event.stopPropagation();\n      onActivate();'), 'Skip-Bo card activation must not bubble into a second global action.');
assert(source.includes("elements.cards.addEventListener('keydown', event =>") && source.includes('event.stopImmediatePropagation()'), 'Duck Race must resolve Enter inside the hand before global roll shortcuts.');
assert(horseRace.includes("el.hand.addEventListener('keydown',event=>") && uno.includes("el.hand.addEventListener('keydown',event=>") && dominoes.includes("el.hand.addEventListener('keydown',event=>") && skipBo.includes("el.hand.addEventListener('keydown', event =>"), 'Every card game must handle Enter at the hand before document-wide shortcuts.');
assert(source.includes("['Mud Puddle', 'Tailwind Tile', 'Feather Cache', 'Lucky Lily Pad', 'Counter Current', 'Deep Whirlpool', 'Feather Snare', 'Card Spring', 'Slingshot Pad'].includes(card)") && source.includes('playCard(card, null, me.square)'), 'Every placed Duck Race action card must be dropped on the current player square.');
assert(source.includes('if (isNowMyTurn && !wasMyTurn)') && source.includes("elements.cards.querySelector('[data-hand-action=\"roll\"]')"), 'A Duck Race turn handoff must restore accessible focus to Roll the Dice.');
assert(horseRace.includes('DerbyEngine.CARDS[pendingCard]?.placement') && horseRace.includes('will be placed on the selected opponent’s current square') && !horseRace.includes('targetSquare:Number(el.targetSquare.value)'), 'Horse Race placement cards must use the selected horse’s current square.');
assert(server.includes("'Mud Puddle'") && server.includes('placedHazards') && server.includes('targetSquare = duck.square'), 'The server must place Duck Race board cards on the player’s current square.');
assert(server.includes('const square=target.position+1') && server.includes('target.mudHazards.add(square)'), 'The server must place Horse Race lane cards on the selected horse’s current square.');
assert(server.includes("'Tailwind Tile'") && server.includes("'Feather Cache'") && server.includes('DUCK_PLACED_CARDS'), 'Duck Race must include multiple square-placement action cards.');
assert(horseEngine.includes("'Hay Bale'") && horseEngine.includes("'Speed Gate'") && horseEngine.includes('placement:true'), 'Horse Race must include multiple lane-square action cards.');
assert(server.includes('resolveDerbyLaneCard(player)') && server.includes('placedCards:Object.fromEntries'), 'Horse Race placed cards must synchronize and activate on landing.');
assert(horseRace.includes('isNowMyTurn&&!wasMyTurn') && horseRace.includes("el.hand.querySelector('[data-hand-action=\"roll\"]')?.focus()"), 'A Horse Race turn handoff must restore accessible focus to Roll the Dice.');
assert((server.match(/name: 'Race Day Trivia'/g) || []).length >= 6 && server.includes('What is a young horse called?') && server.includes('Which bird has webbed feet'), 'Duck Race and Horse Race must share a rotating multi-question trivia mini-game.');
assert(server.includes('participantIds') && server.includes('answerOrder') && server.includes('canAnswer: isParticipant && !hasAnswered'), 'Race mini-games must include every connected player and track one answer per participant.');
assert(source.includes('mini.canAnswer') && horseRace.includes('mini.canAnswer') && source.includes('mini.participantCount') && horseRace.includes('mini.participantCount'), 'Duck Race and Horse Race must show competitive mini-game answers and progress to every participant.');
assert(server.includes('You already played one card this turn. Roll the dice now.') && source.includes('game.cardPlayedThisTurn') && horseRace.includes('game.cardPlayedThisTurn'), 'Both race games must enforce one optional card followed by the dice roll.');
assert(server.includes("'Pond Shortcut'") && server.includes("'Feather Find'") && server.includes("'Trade Places'"), 'Duck Race must offer movement, resource, and position-swap action cards.');
assert(fs.readFileSync(path.join(__dirname, 'horserace-engine.js'), 'utf8').includes("'Backstretch Burst'") && server.includes("cardName==='Position Swap'"), 'Horse Race must offer additional movement and opponent action cards.');
assert(['Quick Paddle','Feather Bonanza','Big Splash','Lucky Lily Pad'].every(card=>server.includes(`'${card}'`)&&source.includes(card)), 'Duck Race must include every expanded action card on both client and server.');
assert(['Current Boost','Feather Swipe','Counter Current'].every(card=>server.includes(`'${card}'`)&&source.includes(card)), 'Duck Race must include new self, opponent, and dropped-current action cards.');
assert(['Deep Whirlpool','Feather Snare','Card Spring','Slingshot Pad'].every(card=>server.includes(`'${card}'`)&&source.includes(card)), 'Duck Race must include backward, feather-loss, card-draw, and forward dropped-square cards.');
assert(server.includes('const DUCK_RACE_LAPS = 3') && server.includes('BOARD_SIZE * DUCK_RACE_LAPS') && source.includes('game.totalLaps || 1'), 'Duck Race must require three laps and announce lap-aware standings before a win.');
assert(['Steady Trot','Rocket Saddle','Headwind','Trip Wire'].every(card=>horseEngine.includes(card)) && server.includes("cardName==='Headwind'") && server.includes("placed.card==='Trip Wire'"), 'Horse Race must include and resolve every expanded action card.');
assert(server.includes('RACE_MINI_GAMES') && server.includes("socket.on('ducks-race-mini-answer'") && server.includes("socket.on('derby-mini-answer'"), 'Both race games must provide synchronized multiplayer mini-games.');
assert(html.includes('id="mini-options"') && fs.readFileSync(path.join(__dirname, 'horserace.html'), 'utf8').includes('id="mini-options"'), 'Both race games must expose keyboard and visual mini-game answer controls.');
assert(source.includes('function renderMiniGame()') && horseRace.includes('function renderMiniGame()'), 'Both race clients must render and focus accessible mini-game choices.');
assert(source.includes('elements.miniOptions.contains(event.target)'), 'Duck Race mini-game keys must not fall through to the card shortcuts.');
assert(source.includes('event.stopPropagation();const buttons=[...elements.miniOptions') && horseRace.includes("event.stopPropagation();const buttons=[...options.querySelectorAll('button:not(:disabled)')]"), 'Mini-game arrow navigation must stop before global keyboard handlers can steal focus.');
assert(source.includes('function handleMiniGameKey(event)') && source.includes('if (handleMiniGameKey(event)) return;') && horseRace.includes('function handleMiniGameKey(event)') && horseRace.includes("event.stopImmediatePropagation()},true)"), 'Every participant must be able to enter mini-game answers with Up or Down and submit with Enter even when initial focus stays elsewhere.');
const life=fs.readFileSync(path.join(__dirname,'life.js'),'utf8');
assert(life.includes("pending&&['arrowup','arrowdown','arrowleft','arrowright'].includes(key)") && life.includes("pending&&event.key==='Enter'"), 'Life route choices must support Up and Down selection followed by Enter.');
assert(['playDuckSplash','playFeatherRustle','playMudSquelch','playHorseHoofbeats','playHorseNeigh','playRaceChallenge'].every(name=>audioSource.includes(`window.${name}`)), 'Shared audio must expose distinct duck, horse, terrain, feather, and mini-game sounds.');
assert(source.includes('playDuckSplash') && source.includes('playDuckQuack') && source.includes('playFeatherRustle') && source.includes('playMudSquelch'), 'Duck Race must sound duck, water, feather, and mud actions.');
assert(horseRace.includes('playHorseHoofbeats') && horseRace.includes('playHorseNeigh') && horseRace.includes('playRaceChallenge'), 'Horse Race must sound movement, finishes, and shared mini-game challenges.');
assert(server.includes("miniGame:true") && server.includes('cue.miniGame = true'), 'Both race servers must send a synchronized mini-game sound cue.');
assert(html.includes('<script src="audio.js"></script>') && horseHtml.includes('<script src="audio.js"></script>'), 'Duck Race and Horse Race must load their synchronized animal and action sound library.');
assert(fs.readFileSync(path.join(__dirname, 'monopoly.js'), 'utf8').includes('playMonopolyEditionCue') && fs.readFileSync(path.join(__dirname, 'uno.js'), 'utf8').includes('playUnoCardSlide'), 'Monopoly editions and UNO variants must retain their tailored theme and card sounds.');
assert(dominoes.includes('function sound(cue)') && skipBo.includes('cue(payload.cue?.type)') && fs.readFileSync(path.join(__dirname, 'life.js'), 'utf8').includes('spinnerSound') && fs.readFileSync(path.join(__dirname, 'mallmadness.js'), 'utf8').includes('function sound(cue,message)'), 'Dominoes, Skip-Bo, Life, and Mall Madness must retain distinct action sound systems.');

console.log('Card-hand and player-target accessibility checks passed for every card game.');
