'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, 'ducks-race.html'), 'utf8');
const source = fs.readFileSync(path.join(__dirname, 'ducks-race.js'), 'utf8');
const skipBo = fs.readFileSync(path.join(__dirname, 'skipbo.js'), 'utf8');
const horseRace = fs.readFileSync(path.join(__dirname, 'horserace.js'), 'utf8');
const dominoes = fs.readFileSync(path.join(__dirname, 'dominoes.js'), 'utf8');
const uno = fs.readFileSync(path.join(__dirname, 'uno.js'), 'utf8');
const server = fs.readFileSync(path.join(__dirname, 'server.js'), 'utf8');
const skipBoHtml = fs.readFileSync(path.join(__dirname, 'skipbo.html'), 'utf8');

assert.match(html, /id="cards"[^>]*role="listbox"[^>]*aria-label="Your cards"/, 'The Duck Race hand must be exposed as a named listbox.');
assert(source.includes("item.setAttribute('role', 'option')"), 'Each Duck Race card must be exposed as an option.');
assert(source.includes('item.tabIndex = index === selectedCardIndex ? 0 : -1'), 'Only the selected card should be in the tab order.');
assert(source.includes("item.setAttribute('aria-selected', String(index === selectedCardIndex))"), 'The selected card must be conveyed to screen readers.');
assert(source.includes("if (event.key === 'ArrowUp' || event.key === 'ArrowDown')") && source.includes('else cycleCard(direction)'), 'Up and Down must cycle through the hand.');
assert(html.includes("role=\"listbox\" aria-label=\"Card targets\"") && source.includes("item.setAttribute('aria-selected', String(index === selectedTargetIndex))"), 'Duck Race player targets must expose selection to screen readers.');
assert(skipBo.includes('li.tabIndex = selection.source === \'hand\'') && skipBo.includes('el.hand.children[index]?.focus()'), 'Skip-Bo arrows must move screen-reader focus through the hand.');
assert(horseRace.includes("b.setAttribute('aria-label',`${cardText(name)} Card ${index+1} of ${game.myHand.length}.`)") && horseRace.includes("b.setAttribute('aria-disabled',String(!active))"), 'Horse Race cards must stay readable outside the player turn.');
assert(dominoes.includes("button.setAttribute('aria-label',`${tileText(shown)}. Tile ${index+1} of ${game.myHand.length}. Press Enter to play.`)") && dominoes.includes("button.setAttribute('aria-disabled',String(!active))"), 'Domino tiles must stay readable outside the player turn.');
assert(uno.includes("li.setAttribute('role','option')") && uno.includes('li.tabIndex=index===selected?0:-1'), 'UNO and DOS cards must expose focused listbox options.');
assert(source.includes("item.addEventListener('click', () => { selectedTargetIndex = index; activateSelectedTarget(); })"), 'Duck Race targets must activate by click in visual mode.');
assert(skipBoHtml.includes('id="target-options"') && skipBo.includes("button.className = 'target-option'") && skipBo.includes("button.addEventListener('click', () => play(target.type, target.index))"), 'Skip-Bo must expose clickable and keyboard-focusable target choices.');
assert(skipBo.includes("li.addEventListener('click', () => select('hand', index))") && skipBo.includes("item.addEventListener('keydown', event =>"), 'Skip-Bo cards and private piles must be selectable by mouse and keyboard.');
assert(horseRace.includes("el.target.addEventListener('keydown',event=>") && horseRace.includes('el.confirmTarget.click()'), 'Horse Race opponent choices must submit with Enter.');
assert(dominoes.includes("button.addEventListener('click',playSelected)") && dominoes.includes('function playSelected()'), 'Domino tiles must play with Enter or click.');
assert(source.includes("if (elements.cards.contains(document.activeElement))") && source.includes("document.activeElement.closest('[data-card-index]')"), 'Duck Race Enter must activate a focused card instead of rolling.');
assert(source.includes("rollItem.dataset.handAction = 'roll'") && source.includes("'Roll the Dice. Press Enter to roll.'") && source.includes('const handCount = me?.hand.length || 0'), 'Duck Race arrows must include Roll the Dice in the hand choices.');
assert(horseRace.includes('selected=-1') && horseRace.includes("roll.dataset.handAction='roll'") && horseRace.includes("if(selected===-1)") && horseRace.includes('const count=game.myHand.length+1'), 'Horse Race must default to and arrow through Roll the Dice with every hand card.');
assert(html.includes('Use Up or Down to choose Roll the Dice or a card') && fs.readFileSync(path.join(__dirname, 'horserace.html'), 'utf8').includes('Use Up or Down to choose Roll the Dice or a card'), 'Both dice-race hands must explain the combined roll-and-card list.');
assert(horseRace.includes("b.addEventListener('keydown',event=>") && horseRace.includes('event.stopPropagation();selected=index;playSelected()'), 'Horse Race Enter must activate the focused card without reaching global shortcuts.');
assert(dominoes.includes("button.addEventListener('keydown',event=>") && dominoes.includes('event.stopPropagation();selected=index;playSelected()'), 'Domino Enter must activate the focused tile without reaching global shortcuts.');
assert(uno.includes("li.addEventListener('keydown',event=>") && uno.includes('event.stopPropagation();selected=index;playOrDraw()'), 'UNO and DOS Enter must activate the focused card without reaching global shortcuts.');
assert(skipBo.includes('event.stopPropagation();\n      onActivate();'), 'Skip-Bo card activation must not bubble into a second global action.');
assert(source.includes("elements.cards.addEventListener('keydown', event =>") && source.includes('event.stopImmediatePropagation()'), 'Duck Race must resolve Enter inside the hand before global roll shortcuts.');
assert(horseRace.includes("el.hand.addEventListener('keydown',event=>") && uno.includes("el.hand.addEventListener('keydown',event=>") && dominoes.includes("el.hand.addEventListener('keydown',event=>") && skipBo.includes("el.hand.addEventListener('keydown', event =>"), 'Every card game must handle Enter at the hand before document-wide shortcuts.');
assert(source.includes("card === 'Mud Puddle'") && source.includes('targetingSquareCard') && source.includes("playCard(card, null, square)"), 'Duck Race must support selecting a board square for a placed trap card.');
assert(horseRace.includes("pendingCard==='Mud Sling'") && horseRace.includes('targetSquare:Number(el.targetSquare.value)'), 'Horse Race Mud Sling must expose an exact lane-square choice.');
assert(server.includes("'Mud Puddle'") && server.includes('placedHazards') && server.includes('targetSquare = Number(data.targetSquare)'), 'The server must store and trigger placed Duck Race board cards.');
assert(server.includes('requested=Number(data.targetSquare)') && server.includes('target.mudHazards.add(hazard)'), 'The server must honor a selected Horse Race Mud Sling square.');
assert(server.includes("'Pond Shortcut'") && server.includes("'Feather Find'") && server.includes("'Trade Places'"), 'Duck Race must offer movement, resource, and position-swap action cards.');
assert(fs.readFileSync(path.join(__dirname, 'horserace-engine.js'), 'utf8').includes("'Backstretch Burst'") && server.includes("cardName==='Position Swap'"), 'Horse Race must offer additional movement and opponent action cards.');
assert(server.includes('RACE_MINI_GAMES') && server.includes("socket.on('ducks-race-mini-answer'") && server.includes("socket.on('derby-mini-answer'"), 'Both race games must provide synchronized multiplayer mini-games.');
assert(html.includes('id="mini-options"') && fs.readFileSync(path.join(__dirname, 'horserace.html'), 'utf8').includes('id="mini-options"'), 'Both race games must expose keyboard and visual mini-game answer controls.');
assert(source.includes('function renderMiniGame()') && horseRace.includes('function renderMiniGame()'), 'Both race clients must render and focus accessible mini-game choices.');

console.log('Card-hand and player-target accessibility checks passed for every card game.');
