'use strict';
const GAME_PAGE_HELP={
'/ducks-race.html':{name:'Duck Race',how:'Race once around the 40-space pond. Roll on your turn, collect feathers, and use cards to protect yourself or slow opponents. The first duck to complete the loop wins.',keys:'Enter rolls. C opens cards. Up and Down choose cards and targets. F reports feathers. Escape closes a selection.'},
'/monopoly.html':{name:'Monopoly',how:'Move around the selected board, buy properties, collect rent, trade, and remain solvent. Every player uses a unique themed token. The last player who has not gone bankrupt wins.',keys:'Arrow Keys explore the board. Enter rolls. F reports balance. P reports your owned properties, their color groups, and how many more properties you need to complete each set. H reports the room. Y buys or accepts an offer. N declines.'},
'/uno.html':{name:'UNO and DOS',how:'Match color, number, or symbol and empty your hand. The chosen variant controls the deck and special rules. Make required UNO or DOS declarations before another player catches you.',keys:'Up and Down choose a card. Space marks a DOS combination. Enter plays or draws. C reports center. H reads hand. S reads scores. U declares UNO. D declares DOS.'},
'/life.html':{name:'The Game of Life',how:'Spin and follow the branching path through careers, family events, investments, and retirement. Follow the selected board theme and finish with the strongest result.',keys:'S or Enter spins. C describes the tile and card. H reports player statistics. Left and Right choose a fork.'},
'/horserace.html':{name:'Horse Race',how:'Race through six laps while terrain and lap events change the track. The first horse to complete all six laps wins.',keys:'Enter, D, or Space rolls the dice and moves automatically. C describes space and lap. S reads standings.'},
'/dominoes.html':{name:'Dominoes',how:'Play a matching tile on either open end. Draw or pass when no tile can be played. The selected set and mode control the tiles and scoring.',keys:'Left and Right choose a tile. Up and Down flip it. L or 1 plays left. R or 2 plays right. C reads ends. B reads board. H reads hand. D or Space draws or passes.'},
'/skipbo.html':{name:'Skip-Bo',how:'Build shared piles in order from 1 through 12. Use cards from your hand, stock pile, and discard piles. Empty your stock pile first to win.',keys:'Up and Down choose a hand card. S selects stock. 1 through 4 select discards. Enter or Space plays. B reads buildings. D reads discards. O reads opponents.'},
'/mallmadness.html':{name:'Mall Madness',how:'Move through the mall, shop for the items on your private list, and manage your cash. Complete your shopping list before the other players.',keys:'S presses the electronic director. Arrow Keys move. Enter swipes or uses an ATM. L reads shopping list. C reports position. O reads opponents.'}
};
const GAME_OPTIONS={
  '/ducks-race.html':{item:'duck',first:'Duck type',second:'Duck color',types:['Mallard','Rubber Duck','Wood Duck','Mandarin Duck','Pekin Duck','Muscovy Duck','Duckling'],colors:['Green and brown','Black','White','Gray','Brown','Blue','Yellow','Red','Purple','Pink','Orange'],cards:true,feathers:true},
  '/horserace.html':{item:'horse',first:'Horse type',second:'Horse color',types:['Miniature Horse','Shetland Pony','Miniature Appaloosa','Full-size Thoroughbred','Full-size Arabian','Full-size Quarter Horse','Full-size Clydesdale'],colors:['Black','White','Gray','Brown','Chestnut','Bay','Palomino','Pinto'],cards:true},
  '/monopoly.html':{item:'Monopoly game',first:'Board edition',second:'Token',types:['Classic','Mega Edition','Electronic Banking','Super Mario','Star Wars','Disney','World Edition'],colors:['Car','Dog','Hat','Boot','Ship','Thimble']},
  '/uno.html':{item:'UNO game',first:'UNO or DOS rules',second:'Deck style',types:['Classic Uno','Uno Flip!','Uno Dos',"Show 'Em No Mercy",'Uno Attack'],colors:['Standard deck']},
  '/life.html':{item:'Game of Life',first:'Board theme',second:'Rules',types:['Classic 1960','Modern Electronic','Super Mario',"Broadcaster's Playground",'Space Colonization','Retro Pop Culture'],colors:['Standard rules']},
  '/dominoes.html':{item:'Dominoes game',first:'Domino set',second:'Domino rules',types:['Double-Six','Double-Nine'],colors:['Draw Game','Block Game','All Fives']},
  '/skipbo.html':{item:'Skip-Bo game',first:'Game pace',second:'Rules',types:['Standard game','Quick game'],colors:['Standard rules']},
  '/mallmadness.html':{item:'Mall Madness game',first:'Shopping challenge',second:'Rules',types:['Standard shopping list','Quick shopping list'],colors:['Standard rules']}
};
document.addEventListener('DOMContentLoaded',()=>{
  const help=GAME_PAGE_HELP[location.pathname],gameOptions=GAME_OPTIONS[location.pathname];if(!help)return;
  const yesNoHelp='';
  const style=document.createElement('style');style.textContent='.game-help-bar{display:flex;flex-wrap:wrap;gap:.65rem;margin:1rem 0}.game-help-dialog{width:min(44rem,92vw);max-height:82vh;overflow:auto;border:3px solid #8b8578;background:#ece6d9;color:#111;padding:1.2rem;box-shadow:inset 1px 1px 0 #fffdf5,inset -1px -1px 0 #b7b0a3}.game-help-dialog::backdrop{background:#0008}.game-help-dialog button{min-height:3rem;border:1px solid #8b8578;background:linear-gradient(180deg,#f9f6ed 0%,#d7d0c0 100%);color:#111;font-weight:700}.game-start-prompt{width:min(42rem,92vw);border:3px solid #8b8578;background:#ece6d9;color:#111;padding:1rem;box-shadow:inset 1px 1px 0 #fffdf5,inset -1px -1px 0 #b7b0a3}.game-start-prompt::backdrop{background:#0008}.game-start-prompt>p{font-size:1.1rem;font-weight:700;margin:.2rem 0}.game-yes-no-buttons{display:none!important}.game-yes-no-buttons button{min-width:10rem;border:1px solid #8b8578;background:linear-gradient(180deg,#f9f6ed 0%,#d7d0c0 100%);color:#111;font-weight:800}';document.head.append(style);
  const bar=document.createElement('nav');bar.className='game-help-bar';bar.setAttribute('aria-label','Game help and navigation');
  const how=document.createElement('button'),keys=document.createElement('button'),quit=document.createElement('button');how.type=keys.type=quit.type='button';how.textContent='How to Play';keys.textContent='Keyboard Commands';quit.textContent='Quit Game (Q)';bar.append(how,keys,quit);document.querySelector('main')?.insertBefore(bar,document.querySelector('main').firstChild);
  const dialog=document.createElement('dialog');dialog.className='game-help-dialog';dialog.setAttribute('aria-labelledby','game-help-title');const title=document.createElement('h2');title.id='game-help-title';const content=document.createElement('p');content.tabIndex=-1;content.setAttribute('role','status');content.setAttribute('aria-live','assertive');const close=document.createElement('button');close.type='button';close.textContent='Close Help';dialog.append(title,content,close);document.body.append(dialog);
  const startDialog=document.createElement('dialog');startDialog.className='game-start-prompt';startDialog.setAttribute('aria-label','Game setup question');const startContent=document.createElement('p');startContent.tabIndex=-1;startContent.setAttribute('role','status');startContent.setAttribute('aria-live','assertive');const yesNoRow=document.createElement('div'),yesButton=document.createElement('button'),noButton=document.createElement('button');yesNoRow.className='game-yes-no-buttons';yesButton.type=noButton.type='button';yesButton.textContent='Yes';noButton.textContent='No';yesNoRow.append(yesButton,noButton);const optionsForm=document.createElement('form');optionsForm.hidden=true;const typeLabel=document.createElement('label'),typeSelect=document.createElement('select'),colorLabel=document.createElement('label'),colorSelect=document.createElement('select'),cardsLabel=document.createElement('label'),cardsSelect=document.createElement('select'),feathersLabel=document.createElement('label'),feathersSelect=document.createElement('select'),saveOptions=document.createElement('button');typeSelect.id='game-option-primary';typeSelect.name='type';typeLabel.htmlFor=typeSelect.id;typeLabel.textContent='Racer type';colorSelect.id='game-option-secondary';colorSelect.name='color';colorLabel.htmlFor=colorSelect.id;colorLabel.textContent='Racer color';cardsSelect.id='game-option-cards';cardsLabel.htmlFor=cardsSelect.id;cardsLabel.textContent='Starting cards';cardsSelect.replaceChildren(new Option('2 cards','2'),new Option('3 cards','3'),new Option('5 cards','5'));cardsSelect.value='3';feathersSelect.id='game-option-feathers';feathersLabel.htmlFor=feathersSelect.id;feathersLabel.textContent='Starting feathers';feathersSelect.replaceChildren(new Option('3 feathers','3'),new Option('5 feathers','5'),new Option('8 feathers','8'));feathersSelect.value='5';saveOptions.type='submit';saveOptions.textContent='Save Game Options';optionsForm.append(typeLabel,typeSelect,colorLabel,colorSelect,cardsLabel,cardsSelect,feathersLabel,feathersSelect,saveOptions);startDialog.append(startContent,yesNoRow,optionsForm);document.body.append(startDialog);
  startDialog.setAttribute('role','application');startDialog.setAttribute('aria-modal','true');startDialog.tabIndex=-1;
  let returnFocus=how,startStage='how',speaking=false,lastPromptKey='',lastPromptKeyTime=0;
  style.textContent+=' .game-setup-display{display:flex;align-items:center;justify-content:center;min-height:18rem;margin-bottom:1rem;background:#000;color:#00ff00;font-family:"Courier New",Courier,monospace;text-align:center}.game-visual-prompt{width:min(600px,100%);padding:40px;border:2px solid #00ff00;border-radius:8px;background:#0a0a0a;box-shadow:0 0 15px rgba(0,255,0,.2)}.game-visual-prompt h2{margin:0 0 .75rem;color:#00ff00}.game-prompt-text{min-height:1.8rem;margin:0 0 20px;color:#fff;font-size:22px;font-weight:800;line-height:1.5}.game-prompt-hint{margin:15px 0 0;color:#aaa;font-size:16px;font-weight:700}.game-prompt-source,.game-prompt-sr{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}';
  style.textContent+=' body.rs-clean-gameplay .lounge-client-shell{display:none!important}';
  const setupState={active:true,step:'INSTRUCTIONS',game:help.name};window.gameSetupState=setupState;
  const setupDisplay=document.createElement('div'),setupAnnouncer=document.createElement('div'),visualPrompt=document.createElement('div'),setupTitle=document.createElement('h2'),promptDisplay=document.createElement('p'),promptHint=document.createElement('p');setupDisplay.className='game-setup-display';setupAnnouncer.className='game-prompt-sr';setupAnnouncer.setAttribute('role','alert');setupAnnouncer.setAttribute('aria-live','assertive');setupAnnouncer.setAttribute('aria-atomic','true');visualPrompt.className='game-visual-prompt';setupTitle.textContent=`${help.name} Setup`;promptDisplay.className='game-prompt-text';promptDisplay.textContent='Loading game prompt...';promptHint.className='game-prompt-hint';promptHint.textContent='[ Press Y for Yes | Press N for No ]';visualPrompt.append(setupTitle,promptDisplay,promptHint);setupDisplay.append(setupAnnouncer,visualPrompt);startDialog.insertBefore(setupDisplay,startContent);startContent.classList.add('game-prompt-source');startContent.removeAttribute('role');startContent.setAttribute('aria-live','off');
  let previousSetupText='';function syncSetupDisplay(){const text=startContent.textContent.trim();setupState.active=startDialog.open;setupState.step=!startDialog.open?'LOBBY':startStage==='how'?'INSTRUCTIONS':startStage==='keys'?'KEYBOARD':'OPTIONS';if(!text||text===previousSetupText)return;previousSetupText=text;promptDisplay.textContent=text;setupAnnouncer.textContent='';requestAnimationFrame(()=>{setupAnnouncer.textContent=text})}new MutationObserver(syncSetupDisplay).observe(startContent,{childList:true,characterData:true,subtree:true});new MutationObserver(syncSetupDisplay).observe(startDialog,{attributes:true,attributeFilter:['open']});
  function syncDesktopPromptMode(){const active=startDialog.open&&['how','keys','options','computer','ready'].includes(startStage);window.loungeDesktopPromptKeys?.setActive(active);if(active)startDialog.focus()}new MutationObserver(syncDesktopPromptMode).observe(startContent,{childList:true,characterData:true,subtree:true});new MutationObserver(syncDesktopPromptMode).observe(startDialog,{attributes:true,attributeFilter:['open']});
  function open(kind,button){returnFocus=button;title.textContent=`${help.name}: ${kind==='how'?'How to Play':'Keyboard Commands'}`;content.textContent=kind==='keys'?`${help.keys} ${yesNoHelp} F2 opens the player count and player list. F3 opens game chat. Q quits the game and returns to the main game list.`:help[kind];dialog.showModal();close.focus()}
  function quitGame(){if(window.LoungeAccessibility?.leaveGameAndReturn)return window.LoungeAccessibility.leaveGameAndReturn();sessionStorage.removeItem('loungeGameId');location.href='/'}
  function announcePrompt(text){if(!text)return;startContent.textContent=String(text);if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(String(text));utterance.rate=1;utterance.pitch=1;window.speechSynthesis.speak(utterance)}
  function ask(stage){startStage=stage;optionsForm.hidden=true;yesNoRow.hidden=true;const duck=help.name==='Duck Race';startContent.textContent=stage==='how'?(duck?'Would you like to hear the instructions for Duck Race?':'Instructions?'):stage==='keys'?(duck?'Would you like to hear the keyboard commands for Duck Race?':'Keyboard commands?'):stage==='computer'?'Add one computer opponent?':(duck?'Would you like to configure Duck Race game options?':'Game options?');startContent.textContent+=' Press Y for yes or N for no.';startContent.focus();announcePrompt(startContent.textContent)}
  function parseYesNoKey(event){if(event.altKey||event.ctrlKey||event.metaKey)return null;const key=String(event.key||'').toLowerCase();if(key==='y'||key==='n')return key;const code=String(event.code||'').toLowerCase();if(code==='keyy')return'y';if(code==='keyn')return'n';const keyCode=Number(event.keyCode||event.which||0);if(keyCode===89)return'y';if(keyCode===78)return'n';const identifier=String(event.keyIdentifier||'').toUpperCase();if(identifier==='U+0059')return'y';if(identifier==='U+004E')return'n';return null}
  function remindYesNo(){if(startStage==='how')startContent.textContent='Instructions?';else if(startStage==='keys')startContent.textContent='Keyboard commands?';else if(startStage==='options')startContent.textContent='Game options?';else if(startStage==='computer')startContent.textContent='Add one computer opponent?';startContent.textContent+=' Press Y for yes or N for no.';startContent.focus();announcePrompt(startContent.textContent)}
  function ensurePromptVisible(){const message=arguments[0]||'';if(!startDialog||typeof startDialog.showModal!=='function')return;if(message){startContent.textContent=message;announcePrompt(message)}if(!startDialog.open)startDialog.showModal();startDialog.focus();syncDesktopPromptMode()}
  function closePrompts(){speaking=false;startStage=null;window.speechSynthesis?.cancel();yesNoRow.hidden=true;if(startDialog.open)startDialog.close();document.querySelector('main')?.focus()}
  function reopenReadyPrompt(message){if(startStage===null)return;startStage='ready';const promptMessage=message||'The game did not start. Press Enter to try again.';ensurePromptVisible(promptMessage)}
  function startGameFromPrompt(attempt=0){if(typeof room!=='undefined'&&Array.isArray(room?.players)&&room.players.length<2){announcePrompt('At least two players are required. Add a computer player or wait for another player, then press Enter to try again.');startDialog.focus();return}const start=document.getElementById('start');if(start&&!start.hidden&&!start.disabled){startStage='starting';ensurePromptVisible('Starting the game. Please wait for server confirmation.');if(startDialog.open)startDialog.close();start.focus({preventScroll:true});start.click();setTimeout(()=>{if(startStage==='starting')reopenReadyPrompt('The server did not confirm the game start. Press Enter to try again.')},3000);return}if(attempt<20){setTimeout(()=>startGameFromPrompt(attempt+1),150);return}reopenReadyPrompt('The game cannot start yet. Make sure enough players have joined, then press Enter to try again.')}
  window.startLoungeGameFromPrompt=key=>{if(String(key||'').toLowerCase()!=='enter'||startStage!=='ready')return false;startGameFromPrompt();return true};
  function finishPrompts(){speaking=false;window.speechSynthesis?.cancel();yesNoRow.hidden=true;optionsForm.hidden=true;if(isHost()){startStage='ready';yesButton.textContent='Start Game';yesButton.hidden=false;noButton.hidden=true;yesNoRow.hidden=false;ensurePromptVisible('Setup complete. Start Game is focused. Press Enter to start the game.');requestAnimationFrame(()=>yesButton.focus())}else{startStage='waiting';ensurePromptVisible('Setup complete. Waiting for the host to start the game.')}}
  function setCleanGameplayLayout(active){document.body.classList.toggle('rs-clean-gameplay',Boolean(active))}
  window.addEventListener('lounge-gameplay-started',()=>{setCleanGameplayLayout(true);if(startStage==='ready'){ensurePromptVisible('Game started. The first player can begin.');setTimeout(()=>{if(startStage==='ready')closePrompts()},1400)}else if(startStage==='waiting'){ensurePromptVisible('Game started. Waiting for the first turn.');setTimeout(()=>{if(startStage==='waiting')closePrompts()},1400)}else if(startStage){closePrompts()}});
  function speak(text,done){speaking=true;startContent.textContent=text;startContent.focus();const fallbackDuration=Math.max(2500,text.length*45),started=Date.now(),finish=()=>{const elapsed=Date.now()-started;setTimeout(done,Math.max(0,(elapsed<500?fallbackDuration:0)-elapsed))};if('speechSynthesis'in window){window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=1;utterance.pitch=1;utterance.onend=finish;utterance.onerror=finish;window.speechSynthesis.speak(utterance)}else setTimeout(done,fallbackDuration)}
  function isHost(){if(typeof room==='undefined'||!room)return false;if(typeof playerId!=='undefined'&&room.hostId===playerId)return true;const host=room.players?.find(player=>player.id===room.hostId),localName=sessionStorage.getItem('loungeUsername');return Boolean(host&&localName&&host.name===localName)}
  function continueAfterOptions(){if(isHost())ask('computer');else finishPrompts()}
  function refreshSecondaryOptions(){if(location.pathname==='/monopoly.html'&&window.MonopolyBoards){const tokens=MonopolyBoards.tokens[typeSelect.value]||[];colorSelect.replaceChildren(...tokens.map(token=>new Option(token.name,token.id)))}else colorSelect.replaceChildren(...gameOptions.colors.map(value=>new Option(value,value)))}
  function visibleOptionControls(){return [typeSelect,colorSelect,cardsSelect,feathersSelect].filter(control=>!control.hidden&&!control.disabled)}
  function nextVisibleOption(currentControl){const controls=visibleOptionControls(),index=controls.indexOf(currentControl);return index>=0?controls[index+1]||null:null}
  function selectByShortcut(control,key){const options=[...control.options],normalized=String(key||'').toLowerCase();if(!normalized)return false;const matches=options.filter(option=>option.textContent.trim().toLowerCase().startsWith(normalized)||String(option.value||'').toLowerCase().startsWith(normalized));if(!matches.length)return false;const current=control.options[control.selectedIndex],currentIndex=matches.findIndex(option=>option===current),next=currentIndex>=0?matches[(currentIndex+1)%matches.length]:matches[0];control.value=next.value;control.dispatchEvent(new Event('change',{bubbles:true}));return true}
  function moveOptionSelection(control,event){if(control?.tagName!=='SELECT'||!control.options.length)return false;const key=String(event.key||event.code||'').toLowerCase(),keyCode=Number(event.keyCode||event.which||0),down=key==='arrowdown'||key==='down'||keyCode===40,up=key==='arrowup'||key==='up'||keyCode===38,home=key==='home'||keyCode===36,end=key==='end'||keyCode===35,pageDown=key==='pagedown'||keyCode===34,pageUp=key==='pageup'||keyCode===33;if(!down&&!up&&!home&&!end&&!pageDown&&!pageUp)return false;const enabled=[...control.options].map((option,index)=>({option,index})).filter(item=>!item.option.disabled);if(!enabled.length)return true;const currentPosition=Math.max(0,enabled.findIndex(item=>item.index===control.selectedIndex));let nextPosition=currentPosition;if(home)nextPosition=0;else if(end)nextPosition=enabled.length-1;else if(down)nextPosition=Math.min(enabled.length-1,currentPosition+1);else if(up)nextPosition=Math.max(0,currentPosition-1);else if(pageDown)nextPosition=Math.min(enabled.length-1,currentPosition+5);else if(pageUp)nextPosition=Math.max(0,currentPosition-5);control.selectedIndex=enabled[nextPosition].index;control.dispatchEvent(new Event('change',{bubbles:true}));const label=document.querySelector(`label[for="${control.id}"]`)?.textContent||'Option';announcePrompt(`${label}: ${control.options[control.selectedIndex].textContent}. Press Enter to save.`);control.focus();return true}
  function applyOptionShortcut(key){const controls=visibleOptionControls();if(!controls.length)return false;const active=document.activeElement,currentControl=controls.includes(active)?active:controls[0],changed=selectByShortcut(currentControl,key);if(!changed)return false;const label=document.querySelector(`label[for="${currentControl.id}"]`)?.textContent||'Option';startContent.textContent=`${label}: ${currentControl.options[currentControl.selectedIndex]?.textContent||currentControl.value}. Press Enter to save.`;currentControl.focus();announcePrompt(startContent.textContent);return true}
  function submitOptionSelection(advance=false,currentControl=null){socket.emit('set-game-options',{type:typeSelect.value,secondary:colorSelect.value,startingCards:Number(cardsSelect.value),startingFeathers:Number(feathersSelect.value)},result=>{if(!result.ok){startContent.textContent=result.error;startContent.focus();announcePrompt(startContent.textContent);return}if(advance&&currentControl){const nextControl=nextVisibleOption(currentControl);if(nextControl){const nextLabel=document.querySelector(`label[for="${nextControl.id}"]`)?.textContent||'Next option';startContent.textContent=`Saved. ${nextLabel}. Use arrow keys, then Enter to save.`;startContent.focus();announcePrompt(startContent.textContent);requestAnimationFrame(()=>nextControl.focus());return}}startContent.textContent=result.message;startContent.focus();announcePrompt(startContent.textContent);continueAfterOptions()})}
  function showGameOptions(attempt=0){const monopoly=location.pathname==='/monopoly.html'&&window.MonopolyBoards;if(monopoly&&(typeof room==='undefined'||!room||!Array.isArray(room.players)||room.players.length===0)){startStage='loading';optionsForm.hidden=true;yesNoRow.hidden=true;startContent.textContent='Loading Monopoly table settings. Please wait.';if(attempt<30){setTimeout(()=>showGameOptions(attempt+1),150);return}announcePrompt('Monopoly table settings could not load. Return to the lounge and join or create a Monopoly game first.');setTimeout(finishPrompts,2500);return}startStage='form';optionsForm.hidden=false;yesNoRow.hidden=true;typeLabel.textContent=gameOptions.first;colorLabel.textContent=gameOptions.second;const currentEdition=monopoly&&typeof room!=='undefined'?room?.monopolyEdition:null,choices=monopoly?MonopolyBoards.editions:gameOptions.types;typeSelect.replaceChildren(...choices.map(value=>new Option(value,value)));if(currentEdition)typeSelect.value=currentEdition;typeSelect.disabled=Boolean(monopoly&&room&&!isHost());refreshSecondaryOptions();cardsLabel.hidden=cardsSelect.hidden=!gameOptions.cards;feathersLabel.hidden=feathersSelect.hidden=!gameOptions.feathers;startContent.textContent=monopoly?(isHost()?'Choose the board edition and your token, then save both selections before starting. Changing the board clears every player’s saved token.':'The host controls the board edition. Choose your token for the current board, then save it before the game starts.'):`Choose options for ${gameOptions.item}. Each player chooses personal pieces or colors where available. The host controls shared game settings.`;(typeSelect.disabled?colorSelect:typeSelect).focus()}
  function afterKeys(){ask('options')}
  function answer(answerYes){if(speaking)return;if(startStage==='how'){if(answerYes)speak(`${help.name}. How to play. ${help.how}`,()=>{speaking=false;ask('keys')});else ask('keys')}else if(startStage==='keys'){if(answerYes)speak(`${help.name}. Keyboard commands. ${help.keys} ${yesNoHelp} F2 opens the player count and player list. F3 opens game chat. Q quits the game and returns to the main game list.`,()=>{speaking=false;afterKeys()});else afterKeys()}else if(startStage==='options'){if(answerYes)showGameOptions();else if(isHost())ask('computer');else finishPrompts()}else if(startStage==='computer'){if(!answerYes)return finishPrompts();startContent.textContent='Adding one computer opponent. Please wait.';startContent.focus();socket.emit('add-computer-player',{},result=>{if(!result.ok){startContent.textContent=`${result.error} Press Y to try again or N to continue without a computer.`;startContent.focus();return}startContent.textContent=result.message;finishPrompts()})}}
  window.loungeDesktopPromptKeys?.onKey(key=>{if(startStage==='ready'&&key==='enter'){startGameFromPrompt();return}if(!['how','keys','options','computer'].includes(startStage)||!['y','n'].includes(key))return;answer(key==='y')});
  how.addEventListener('click',()=>open('how',how));keys.addEventListener('click',()=>open('keys',keys));quit.addEventListener('click',quitGame);close.addEventListener('click',()=>{dialog.close();returnFocus.focus()});dialog.addEventListener('cancel',event=>{event.preventDefault();dialog.close();returnFocus.focus()});startDialog.addEventListener('cancel',event=>event.preventDefault());yesButton.addEventListener('click',()=>startStage==='ready'?startGameFromPrompt():answer(true));noButton.addEventListener('click',()=>answer(false));typeSelect.addEventListener('change',refreshSecondaryOptions);optionsForm.addEventListener('submit',event=>{event.preventDefault();submitOptionSelection(false,null)});optionsForm.addEventListener('keydown',event=>{if(event.key!=='Enter')return;const control=event.target;if(!['SELECT','INPUT'].includes(control.tagName))return;event.preventDefault();submitOptionSelection(true,control)});
  function handlePromptKeys(event,isKeyup=false){
    const key=String(event.key||'').toLowerCase(),yesNo=parseYesNoKey(event),target=event.target;
    if(['how','keys','options','computer'].includes(startStage)){
      event.preventDefault();event.stopImmediatePropagation();
      if(!yesNo){if(!isKeyup)remindYesNo();return true}
      if(isKeyup&&lastPromptKey===yesNo&&(event.timeStamp-lastPromptKeyTime)<700)return true;
      lastPromptKey=yesNo;lastPromptKeyTime=event.timeStamp;answer(yesNo==='y');return true;
    }
    if(startStage==='ready'){event.preventDefault();event.stopImmediatePropagation();if(!isKeyup&&event.key==='Enter')startGameFromPrompt();else if(!isKeyup)announcePrompt('Setup complete. Press Enter to start the game.');return true}
    if(startStage==='waiting'){event.preventDefault();event.stopImmediatePropagation();return true}
    if(startStage&&startStage!=='form'){event.preventDefault();event.stopImmediatePropagation();return true}
    if(startStage==='form'){
      if(!isKeyup&&moveOptionSelection(target,event)){event.preventDefault();event.stopImmediatePropagation();return true}
      if(!isKeyup&&!event.altKey&&!event.ctrlKey&&!event.metaKey&&/^[a-z]$/.test(key)&&applyOptionShortcut(key)){event.preventDefault();event.stopImmediatePropagation();return true}
      if(!isKeyup&&event.key==='Enter'){
        const controls=visibleOptionControls(),currentControl=controls.includes(target)?target:controls[0]||null;
        if(currentControl){event.preventDefault();event.stopImmediatePropagation();submitOptionSelection(true,currentControl);return true}
      }
      if(!isKeyup&&event.key!=='Tab'){event.preventDefault();event.stopImmediatePropagation();return true}
      return false;
    }
    if(!isKeyup&&event.key==='F1'){event.preventDefault();open('keys',keys);return true}
    if(!isKeyup&&event.key==='Enter'&&startStage===null&&!dialog.open&&!startDialog.open&&!['BUTTON','A','INPUT','TEXTAREA','SELECT'].includes(target.tagName)){
      const startButton=document.getElementById('start');if(startButton&&!startButton.hidden&&!startButton.disabled){event.preventDefault();startButton.click();return true}
    }
    if(!isKeyup&&key==='q'&&!event.altKey&&!event.ctrlKey&&!event.metaKey&&!dialog.open&&!target.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(target.tagName)){event.preventDefault();quitGame();return true}
    return false;
  }
  document.addEventListener('keydown',event=>{handlePromptKeys(event,false);},true);
  document.addEventListener('keypress',event=>{if(!['how','keys','options','computer'].includes(startStage))return;if(parseYesNoKey(event))handlePromptKeys(event,false);},true);
  document.addEventListener('keyup',event=>{if(['y','n','Y','N'].includes(event.key))handlePromptKeys(event,true);},true);
  if(typeof socket!=='undefined'&&socket&&typeof socket.on==='function')['ducks-race-state','monopoly-state','uno-state','life-state','derby-state','domino-state','skipbo-state','mall-state'].forEach(eventName=>socket.on(eventName,payload=>{const status=payload?.game?.status;if(status==='playing'){if(startDialog.open)finishPrompts();setCleanGameplayLayout(true)}else if(status==='waiting')setCleanGameplayLayout(false)}));
  startDialog.showModal();ask('how');
});
