'use strict';
const GAME_PAGE_HELP={
'/ducks-race.html':{name:"Duck's Race",how:'Race once around the 40-space pond. Roll on your turn, collect feathers, and use cards to protect yourself or slow opponents. The first duck to complete the loop wins.',keys:'Enter rolls. C opens cards. Up and Down choose cards and targets. F reports feathers. Escape closes a selection.'},
'/monopoly.html':{name:'Monopoly',how:'Move around the selected board, buy properties, collect rent, trade, and remain solvent. Every player uses a unique themed token. The last player who has not gone bankrupt wins.',keys:'Arrow Keys explore the board. Enter rolls. F reports balance. P lists properties. H reports the room. Y and N answer offers.'},
'/uno.html':{name:'UNO and DOS',how:'Match color, number, or symbol and empty your hand. The chosen variant controls the deck and special rules. Make required UNO or DOS declarations before another player catches you.',keys:'Up and Down choose a card. Space marks a DOS combination. Enter plays or draws. C reports center. H reads hand. S reads scores. U declares UNO. D declares DOS.'},
'/life.html':{name:'The Game of Life',how:'Spin and follow the branching path through careers, family events, investments, and retirement. Follow the selected board theme and finish with the strongest result.',keys:'S or Enter spins. C describes the tile and card. H reports player statistics. Left and Right choose a fork.'},
'/horserace.html':{name:'Horse Race',how:'Play movement and sabotage cards through six laps. Track terrain and lap events. The first horse to complete all six laps wins.',keys:'Up and Down choose a card. Enter plays. C describes space and lap. S reads standings. D or Space draws.'},
'/dominoes.html':{name:'Dominoes',how:'Play a matching tile on either open end. Draw or pass when no tile can be played. The selected set and mode control the tiles and scoring.',keys:'Left and Right choose a tile. Up and Down flip it. L or 1 plays left. R or 2 plays right. C reads ends. B reads board. H reads hand. D or Space draws or passes.'},
'/skipbo.html':{name:'Skip-Bo',how:'Build shared piles in order from 1 through 12. Use cards from your hand, stock pile, and discard piles. Empty your stock pile first to win.',keys:'Up and Down choose a hand card. S selects stock. 1 through 4 select discards. Enter or Space plays. B reads buildings. D reads discards. O reads opponents.'},
'/mallmadness.html':{name:'Mall Madness',how:'Move through the mall, shop for the items on your private list, and manage your cash. Complete your shopping list before the other players.',keys:'S presses the electronic director. Arrow Keys move. Enter swipes or uses an ATM. L reads shopping list. C reports position. O reads opponents.'}
};
const GAME_OPTIONS={
  '/ducks-race.html':{item:'duck',first:'Duck type',second:'Duck color',types:['Mallard','Rubber Duck','Wood Duck','Mandarin Duck','Pekin Duck','Muscovy Duck','Duckling'],colors:['Green and brown','Black','White','Gray','Brown','Blue','Yellow','Red','Purple','Pink','Orange'],cards:true,feathers:true},
  '/horserace.html':{item:'horse',first:'Horse type',second:'Horse color',types:['Miniature Horse','Shetland Pony','Miniature Appaloosa','Full-size Thoroughbred','Full-size Arabian','Full-size Quarter Horse','Full-size Clydesdale'],colors:['Black','White','Gray','Brown','Chestnut','Bay','Palomino','Pinto'],cards:true},
  '/monopoly.html':{item:'Monopoly game',first:'Board edition',second:'Token',types:['Classic','Mega Edition','Electronic Banking','Super Mario','Star Wars','Disney','World Edition'],colors:['Car','Dog','Hat','Boot','Ship','Thimble']},
  '/uno.html':{item:'UNO game',first:'UNO or DOS rules',second:'Deck style',types:['Classic Uno','Uno Flip!','Uno Dos',"Show 'Em No Mercy",'Uno Attack'],colors:['Standard deck']},
  '/life.html':{item:'Game of Life',first:'Board theme',second:'Rules',types:['Classic 1960','Modern Electronic','Super Mario',"Broadcaster's Playground",'Space Colonization','Retro Pop Culture'],colors:['Standard rules']},
  '/dominoes.html':{item:'Dominoes game',first:'Domino set',second:'Domino rules',types:['Double-Six','Double-Nine'],colors:['Draw Game','Block Game','All Fives']},
  '/skipbo.html':{item:'Skip-Bo game',first:'Game pace',second:'Rules',types:['Standard game','Quick game'],colors:['Standard rules']},
  '/mallmadness.html':{item:'Mall Madness game',first:'Shopping challenge',second:'Rules',types:['Standard shopping list','Quick shopping list'],colors:['Standard rules']}
};
document.addEventListener('DOMContentLoaded',()=>{
  const help=GAME_PAGE_HELP[location.pathname],gameOptions=GAME_OPTIONS[location.pathname];if(!help)return;
  const style=document.createElement('style');style.textContent='.game-help-bar{display:flex;flex-wrap:wrap;gap:.65rem;margin:1rem 0}.game-help-dialog{width:min(44rem,92vw);max-height:82vh;overflow:auto;border:4px solid #ffe14d;background:#101827;color:#fff;padding:1.2rem}.game-help-dialog::backdrop{background:#000b}.game-help-dialog button{min-height:3rem}.start-help-actions{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}';document.head.append(style);
  const bar=document.createElement('nav');bar.className='game-help-bar';bar.setAttribute('aria-label','Game help and navigation');
  const how=document.createElement('button'),keys=document.createElement('button'),quit=document.createElement('button');how.type=keys.type=quit.type='button';how.textContent='How to Play';keys.textContent='Keyboard Commands';quit.textContent='Quit Game (Q)';bar.append(how,keys,quit);document.querySelector('main')?.insertBefore(bar,document.querySelector('main').firstChild);
  const dialog=document.createElement('dialog');dialog.className='game-help-dialog';dialog.setAttribute('aria-labelledby','game-help-title');const title=document.createElement('h2');title.id='game-help-title';const content=document.createElement('p');content.tabIndex=-1;content.setAttribute('role','status');content.setAttribute('aria-live','assertive');const close=document.createElement('button');close.type='button';close.textContent='Close Help';dialog.append(title,content,close);document.body.append(dialog);
  const startDialog=document.createElement('dialog');startDialog.className='game-help-dialog';startDialog.setAttribute('aria-labelledby','start-help-title');const startTitle=document.createElement('h2');startTitle.id='start-help-title';startTitle.textContent='Before Starting the Game';const startContent=document.createElement('p');startContent.tabIndex=-1;startContent.setAttribute('role','status');startContent.setAttribute('aria-live','assertive');const actions=document.createElement('div');actions.className='start-help-actions';const yes=document.createElement('button'),no=document.createElement('button');yes.type=no.type='button';yes.textContent='Yes (Y)';no.textContent='No (N)';actions.append(yes,no);const optionsForm=document.createElement('form');optionsForm.hidden=true;const typeLabel=document.createElement('label'),typeSelect=document.createElement('select'),colorLabel=document.createElement('label'),colorSelect=document.createElement('select'),cardsLabel=document.createElement('label'),cardsSelect=document.createElement('select'),feathersLabel=document.createElement('label'),feathersSelect=document.createElement('select'),saveOptions=document.createElement('button');typeLabel.textContent='Racer type';typeSelect.name='type';colorLabel.textContent='Racer color';colorSelect.name='color';cardsLabel.textContent='Starting cards';cardsSelect.replaceChildren(new Option('2 cards','2'),new Option('3 cards','3'),new Option('5 cards','5'));cardsSelect.value='3';feathersLabel.textContent='Starting feathers';feathersSelect.replaceChildren(new Option('3 feathers','3'),new Option('5 feathers','5'),new Option('8 feathers','8'));feathersSelect.value='5';saveOptions.type='submit';saveOptions.textContent='Save Game Options';optionsForm.append(typeLabel,typeSelect,colorLabel,colorSelect,cardsLabel,cardsSelect,feathersLabel,feathersSelect,saveOptions);startDialog.append(startTitle,startContent,actions,optionsForm);document.body.append(startDialog);
  let returnFocus=how,startStage='how',speaking=false;
  function open(kind,button){returnFocus=button;title.textContent=`${help.name}: ${kind==='how'?'How to Play':'Keyboard Commands'}`;content.textContent=kind==='keys'?`${help.keys} Q quits the game and returns to the main game list.`:help[kind];dialog.showModal();close.focus()}
  function quitGame(){sessionStorage.removeItem('loungeGameId');if(typeof socket!=='undefined'&&socket.connected){socket.emit('leave-room');setTimeout(()=>{location.href='/'},100)}else location.href='/'}
  function ask(stage){startStage=stage;optionsForm.hidden=true;actions.hidden=false;startContent.textContent=stage==='how'?'Would you like to hear how to play? Press Y for yes or N for no.':stage==='keys'?'Would you like to hear the keyboard commands? Press Y for yes or N for no.':'Would you like to set up game options? Press Y for yes or N for no.';yes.focus()}
  function focusStart(attempt=0){const start=document.getElementById('start');if(start&&!start.hidden){start.focus();return}if(attempt<20)setTimeout(()=>focusStart(attempt+1),150);else document.querySelector('main')?.focus()}
  function finishPrompts(){speaking=false;startStage=null;window.speechSynthesis?.cancel();startDialog.close();startContent.textContent='Instructions complete. The host can press Enter to start the game.';focusStart()}
  function speak(text,done){speaking=true;startContent.textContent=text;startContent.focus();if('speechSynthesis'in window){window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.92;utterance.onend=done;utterance.onerror=done;window.speechSynthesis.speak(utterance)}else setTimeout(done,Math.max(2500,text.length*45))}
  function refreshSecondaryOptions(){if(location.pathname==='/monopoly.html'&&window.MonopolyBoards){const tokens=MonopolyBoards.tokens[typeSelect.value]||[];colorSelect.replaceChildren(...tokens.map(token=>new Option(token.name,token.name)))}else colorSelect.replaceChildren(...gameOptions.colors.map(value=>new Option(value,value)))}
  function showGameOptions(){startStage='form';actions.hidden=true;optionsForm.hidden=false;typeLabel.textContent=gameOptions.first;colorLabel.textContent=gameOptions.second;const choices=location.pathname==='/monopoly.html'&&window.MonopolyBoards?MonopolyBoards.editions:gameOptions.types;typeSelect.replaceChildren(...choices.map(value=>new Option(value,value)));refreshSecondaryOptions();cardsLabel.hidden=cardsSelect.hidden=!gameOptions.cards;feathersLabel.hidden=feathersSelect.hidden=!gameOptions.feathers;startContent.textContent=`Choose options for ${gameOptions.item}. Each player chooses personal pieces or colors where available. The host controls shared game settings.`;typeSelect.focus()}
  function afterKeys(){ask('options')}
  function answer(answerYes){if(speaking)return;if(startStage==='how'){if(answerYes)speak(`${help.name}. How to play. ${help.how}`,()=>{speaking=false;ask('keys')});else ask('keys')}else if(startStage==='keys'){if(answerYes)speak(`${help.name}. Keyboard commands. ${help.keys} Q quits the game and returns to the main game list.`,()=>{speaking=false;afterKeys()});else afterKeys()}else if(startStage==='options'){if(answerYes)showGameOptions();else finishPrompts()}}
  how.addEventListener('click',()=>open('how',how));keys.addEventListener('click',()=>open('keys',keys));quit.addEventListener('click',quitGame);close.addEventListener('click',()=>{dialog.close();returnFocus.focus()});dialog.addEventListener('cancel',event=>{event.preventDefault();dialog.close();returnFocus.focus()});yes.addEventListener('click',()=>answer(true));no.addEventListener('click',()=>answer(false));startDialog.addEventListener('cancel',event=>event.preventDefault());typeSelect.addEventListener('change',refreshSecondaryOptions);optionsForm.addEventListener('submit',event=>{event.preventDefault();socket.emit('set-game-options',{type:typeSelect.value,secondary:colorSelect.value,startingCards:Number(cardsSelect.value),startingFeathers:Number(feathersSelect.value)},result=>{if(!result.ok){startContent.textContent=result.error;return}startContent.textContent=result.message;finishPrompts()})});
  document.addEventListener('keydown',event=>{const key=event.key.toLowerCase();if(['how','keys','options'].includes(startStage)&&['y','n'].includes(key)){event.preventDefault();event.stopImmediatePropagation();answer(key==='y');return}if(startStage&&startStage!=='form'){if(event.key==='Enter'||event.key===' '){event.stopImmediatePropagation()}return}if(startStage==='form')return;if(event.key==='F1'){event.preventDefault();open('keys',keys);return}const target=event.target;if(key==='q'&&!event.altKey&&!event.ctrlKey&&!event.metaKey&&!dialog.open&&!target.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(target.tagName)){event.preventDefault();quitGame()}},true);
  startDialog.showModal();ask('how');
});
