'use strict';
const GAME_PAGE_HELP={
'/ducks-race.html':{name:"Duck's Race",how:'Race once around the 40-space pond. Roll on your turn, collect feathers, and use cards to protect yourself or slow opponents. The first duck to complete the loop wins.',keys:'Enter rolls. C opens cards. Up and Down choose cards and targets. F reports feathers. Escape closes a selection.'},
'/monopoly.html':{name:'Monopoly',how:'Move around the selected board, buy properties, collect rent, trade, and remain solvent. Every player uses a unique themed token. The last player who has not gone bankrupt wins.',keys:'Arrow Keys explore the board. Enter rolls. F reports balance. P lists properties. H reports the room. Y and N answer offers.'},
'/uno.html':{name:'UNO and DOS',how:'Match color, number, or symbol and empty your hand. The chosen variant controls the deck and special rules. Make required UNO or DOS declarations before another player catches you.',keys:'Up and Down choose a card. Space marks a DOS combination. Enter plays or draws. C reports center. H reads hand. S reads scores. U declares UNO. D declares DOS.'},
'/life.html':{name:'The Game of Life',how:'Spin and follow the branching path through careers, family events, investments, and retirement. Follow the selected board theme and finish with the strongest result.',keys:'S or Enter spins. C describes the tile and card. H reports player statistics. Left and Right choose a fork.'},
'/horserace.html':{name:'Horse Race',how:'Play movement and sabotage cards through six laps. Track terrain and lap events. The first horse to complete all six laps wins.',keys:'Up and Down choose a card. Enter plays. C describes space and lap. S reads standings. D or Space draws.'},
'/dominoes.html':{name:'Dominoes',how:'Play a matching tile on either open end. Draw or pass when no tile can be played. The selected set and mode control the tiles and scoring.',keys:'Left and Right choose a tile. Up and Down flip it. L or 1 plays left. R or 2 plays right. C reads ends. B reads board. H reads hand. D or Space draws or passes.'},
'/skipbo.html':{name:'Skip-Bo',how:'Build shared piles in order from 1 through 12. Use cards from your hand, stock pile, and discard piles. Empty your stock pile first to win.',keys:'Up and Down choose a hand card. S selects stock. 1 through 4 select discards. Enter or Space plays. B reads buildings. D reads discards. O reads opponents.'},
'/mallmadness.html':{name:'Mall Madness',how:'Move through the mall, shop for the items on your private list, and manage your cash. Complete your shopping list before the other players.',keys:'S presses the electronic director. Arrow Keys move. Enter swipes or uses an ATM. L reads shopping list. C reports position. O reads opponents.'}
};
document.addEventListener('DOMContentLoaded',()=>{const help=GAME_PAGE_HELP[location.pathname];if(!help)return;const style=document.createElement('style');style.textContent='.game-help-bar{display:flex;flex-wrap:wrap;gap:.65rem;margin:1rem 0}.game-help-dialog{width:min(44rem,92vw);max-height:82vh;overflow:auto;border:4px solid #ffe14d;background:#101827;color:#fff;padding:1.2rem}.game-help-dialog::backdrop{background:#000b}.game-help-dialog button{min-height:3rem}';document.head.append(style);const bar=document.createElement('nav');bar.className='game-help-bar';bar.setAttribute('aria-label','Game help');const how=document.createElement('button'),keys=document.createElement('button');how.type=keys.type='button';how.textContent='How to Play';keys.textContent='Keyboard Commands';bar.append(how,keys);const main=document.querySelector('main');main?.insertBefore(bar,main.firstChild);const dialog=document.createElement('dialog');dialog.className='game-help-dialog';dialog.setAttribute('aria-labelledby','game-help-title');const title=document.createElement('h2');title.id='game-help-title';const content=document.createElement('p'),close=document.createElement('button');close.type='button';close.textContent='Close Help';dialog.append(title,content,close);document.body.append(dialog);let returnFocus=how;function open(kind,button){returnFocus=button;title.textContent=`${help.name}: ${kind==='how'?'How to Play':'Keyboard Commands'}`;content.textContent=help[kind];dialog.showModal();close.focus()}how.addEventListener('click',()=>open('how',how));keys.addEventListener('click',()=>open('keys',keys));close.addEventListener('click',()=>{dialog.close();returnFocus.focus()});dialog.addEventListener('cancel',event=>{event.preventDefault();dialog.close();returnFocus.focus()});document.addEventListener('keydown',event=>{if(event.key==='F1'){event.preventDefault();open('keys',keys)}})});
