'use strict';

const socket=io();
const gameId=new URLSearchParams(location.search).get('game')||sessionStorage.getItem('loungeGameId');
const token=sessionStorage.getItem('loungeSessionToken');
const username=sessionStorage.getItem('loungeUsername');
const ids=['connection','start','spin','describe','stats','turn-status','fork','fork-prompt','route-choice','choose','private-assets','players','theme','board','announcer','instant-announcer'];
const el=Object.fromEntries(ids.map(id=>[id.replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),document.getElementById(id)]));
let room=null,game=null,playerId=null,lastSequence=0,selectedRoute=0,audio=null;
const accessibility = window.LoungeAccessibility?.createGameStateController({
	mode: 'GAME',
	statusEl: el.announcer,
	items: [
		{ label: 'Spin', type: 'game' },
		{ label: 'Describe Tile And Card', type: 'game' },
		{ label: 'Hear My Stats', type: 'game' },
		{ label: 'Help / Instructions', type: 'help' }
	],
	hotkeys: { scores: [], players: ['p'], help: ['?'] },
	helpText: 'Keyboard shortcuts: S or Enter spins. C describes your tile and private card details. H reads your player statistics. Left and Right choose a fork route. Press P for connected players.'
});
function context(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audio||=new C();if(audio.state==='suspended')audio.resume().catch(()=>{});return audio}
function tone(notes,wave='sine',volume=.1){const c=context();if(!c)return;const now=c.currentTime;notes.forEach((frequency,index)=>{const o=c.createOscillator(),g=c.createGain(),start=now+index*.09;o.type=wave;o.frequency.value=frequency;g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(volume,start+.008);g.gain.exponentialRampToValueAtTime(.0001,start+.3);o.connect(g).connect(c.destination);o.start(start);o.stop(start+.32)})}
function spinnerSound(result){const c=context();if(!c)return;const now=c.currentTime;let offset=0;for(let i=0;i<22+result;i+=1){const gap=.025+(i*i*.00055);offset+=gap;const o=c.createOscillator(),g=c.createGain(),start=now+offset;o.type='square';o.frequency.value=900+(i%3)*170;g.gain.setValueAtTime(.065,start);g.gain.exponentialRampToValueAtTime(.0001,start+.028);o.connect(g).connect(c.destination);o.start(start);o.stop(start+.03)}return Math.ceil((offset+.08)*1000)}
function cue(type){if(type==='payday')tone([523,659,784,1047],'sine',.13);if(type==='passenger')tone([440,554,659],'triangle',.12);if(type==='house')tone([262,330,392,523],'sine',.12);if(type==='career')tone([392,523,659],'triangle',.1)}
function announce(message,assertive=false){const target=assertive?el.instantAnnouncer:el.announcer;target.textContent='';requestAnimationFrame(()=>{target.textContent=message})}
function me(){return game?.players.find(p=>p.id===playerId)}
function money(value){return LifeThemes.formatMoney(game?.theme||'Classic 1960',value)}
function tile(){return game?.board[me()?.position||0]}
function statsText(){const p=me();if(!p)return 'Player statistics are not available.';return `${p.name}. Career: ${p.career}. Salary: ${money(p.salary)}. Car passenger peg count: ${p.pegs}. Cash: ${money(p.cash)}. House: ${p.house||'none'}. Public property count: ${p.assetCount}. Private financial card count: ${game.myPrivateAssets.length}.`}
function describeText(){const active=tile();return active?`${active.name}. ${active.description}${game.myPrivateAssets?.[0]?` Current private card: ${game.myPrivateAssets[0].name}. ${game.myPrivateAssets[0].description}`:''}`:'No active tile.'}
function syncAccessibilityState(){if(!accessibility||!game)return;accessibility.setPlayers((game.players||[]).map(player=>player.name));accessibility.setScores(Object.fromEntries((game.players||[]).map(player=>[player.name,money(player.cash)])))}
function renderBoard(){const positions=new Map();for(const player of game.players)positions.set(player.position,(positions.get(player.position)||[]).concat(player.name));el.board.replaceChildren(...game.board.map(space=>{const li=document.createElement('li');li.className=`space ${space.type==='fork'?'fork':''} ${positions.has(space.index)?'current':''}`;li.setAttribute('aria-label',`Space ${space.index+1}: ${space.name}. ${space.description}${positions.has(space.index)?` Players here: ${positions.get(space.index).join(', ')}.`:''}`);const number=document.createElement('strong');number.textContent=`${space.index+1}. ${space.name}`;const type=document.createElement('span');type.textContent=space.type;li.append(number,type);return li}))}
function render(){if(!game)return;const mine=me(),myTurn=game.turnPlayerId===playerId,pending=game.pendingChoice?.playerId===playerId;el.theme.textContent=game.theme;el.start.hidden=game.status!=='waiting'||room?.hostId!==playerId;el.spin.disabled=game.status!=='playing'||!myTurn||pending;el.turnStatus.textContent=game.status==='waiting'?'Waiting for the host to start.':game.status==='finished'?game.announcement:pending?'Choose a route with Left or Right Arrow, then press Enter.':myTurn?'It is your turn. Press S or Enter to spin.':`Waiting for ${game.players.find(p=>p.id===game.turnPlayerId)?.name}.`;el.fork.hidden=!pending;if(pending){const choices=game.pendingChoice.options;selectedRoute=Math.min(selectedRoute,choices.length-1);el.routeChoice.replaceChildren(...choices.map((option,index)=>new Option(`${option.name}. ${option.description}`,String(index))));el.routeChoice.selectedIndex=selectedRoute;el.forkPrompt.textContent=`Fork at ${tile().name}. ${choices.length} routes are available.`}el.privateAssets.replaceChildren(...(game.myPrivateAssets.length?game.myPrivateAssets.map(asset=>{const li=document.createElement('li');li.textContent=`${asset.name}: ${asset.description} Private value: ${money(asset.value)}.`;return li}):[Object.assign(document.createElement('li'),{textContent:'No private assets yet.'})]));el.players.replaceChildren(...game.players.map(p=>{const li=document.createElement('li');li.textContent=`${p.name}. ${p.career}. Salary ${money(p.salary)}. ${p.pegs} passenger pegs. Cash ${money(p.cash)}. House ${p.house||'none'}. ${p.assetCount} public properties.${p.id===game.turnPlayerId?' Current turn.':''}`;return li}));renderBoard();if(mine)el.board.children[mine.position]?.scrollIntoView({block:'nearest',inline:'center'});syncAccessibilityState()}
function receive(payload){const fresh=payload.game.sequence!==lastSequence;game=payload.game;if(game.status==='playing'){window.dispatchEvent(new CustomEvent('lounge-gameplay-started'));}const delay=payload.cue?.type==='spinner'?spinnerSound(payload.cue.result):0;if(payload.cue?.secondary)cue(payload.cue.secondary);render();if(fresh&&game.announcement)setTimeout(()=>announce(game.announcement,payload.cue?.secondary==='payday'),delay);lastSequence=game.sequence}
function connect(){if(!token||!gameId){el.connection.textContent='Missing login or game. Return to the lounge.';return}socket.emit('authenticate-token',{token},auth=>{if(!auth.ok){el.connection.textContent=auth.error;return}socket.emit('join-game',{gameId},result=>{if(!result.ok){el.connection.textContent=result.error;return}room=result.room;playerId=room.players.find(p=>p.name===username)?.id||room.players.find(p=>p.name===auth.username)?.id;el.connection.textContent=`Connected to ${room.lifeTheme} Life game ${room.code}.`;if(room.life)receive({game:room.life})})})}
el.start.addEventListener('click',()=>socket.emit('start-life',{},result=>{if(!result.ok)announce(result.error,true)}));
el.spin.addEventListener('click',()=>socket.emit('life-spin',{},result=>{if(!result.ok)announce(result.error,true)}));
el.describe.addEventListener('click',()=>announce(describeText()));el.stats.addEventListener('click',()=>announce(statsText()));
function choose(){socket.emit('life-choose',{choice:selectedRoute},result=>{if(!result.ok)announce(result.error,true)})}el.choose.addEventListener('click',choose);el.routeChoice.addEventListener('change',()=>{selectedRoute=el.routeChoice.selectedIndex;announce(`Selected ${el.routeChoice.options[selectedRoute].text}. Press Enter to take this route.`)});
document.addEventListener('keydown',event=>{if(event.altKey||event.ctrlKey||event.metaKey)return;if(accessibility?.handleKey(event))return;const key=event.key.toLowerCase();const pending=!el.fork.hidden;if(event.key==='Enter'&&game?.status==='waiting'&&room?.hostId===playerId&&!['BUTTON','A','INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName||'')){event.preventDefault();el.start.click();return}if(pending&&(key==='arrowleft'||key==='arrowright')){event.preventDefault();const count=el.routeChoice.options.length;selectedRoute=(selectedRoute+(key==='arrowright'?1:-1)+count)%count;el.routeChoice.selectedIndex=selectedRoute;el.routeChoice.dispatchEvent(new Event('change'));return}if(pending&&event.key==='Enter'&&!['BUTTON'].includes(document.activeElement.tagName)){event.preventDefault();choose();return}if((key==='s'||event.key==='Enter')&&!el.spin.disabled&&!['BUTTON','SELECT','A','INPUT'].includes(document.activeElement.tagName)){event.preventDefault();el.spin.click();return}if(key==='c'){event.preventDefault();el.describe.click()}if(key==='h'){event.preventDefault();el.stats.click()}});
window.addEventListener('pointerdown',context,{once:true});window.addEventListener('keydown',context,{once:true});socket.on('connect',connect);socket.on('lobby-updated',updated=>{room=updated;playerId=playerId||room.players.find(p=>p.name===username)?.id||null;if(!game||game.status==='waiting'){game=room.life||{theme:room.lifeTheme||'Classic 1960',board:[],status:'waiting',turnPlayerId:null,announcement:'Waiting for the host to start Life.',sequence:0,pendingChoice:null,myPrivateAssets:[],players:room.players.map(p=>({...p,career:'Teacher',salary:0,pegs:0,cash:0,house:null,assetCount:0,position:0}))};render();syncAccessibilityState()}});socket.on('table-player-joined',data=>{if(!data?.message)return;if(game?.status==='waiting'){game=room.life||{theme:room.lifeTheme||'Classic 1960',board:[],status:'waiting',turnPlayerId:null,announcement:'Waiting for the host to start Life.',sequence:0,pendingChoice:null,myPrivateAssets:[],players:room.players.map(p=>({...p,career:'Teacher',salary:0,pegs:0,cash:0,house:null,assetCount:0,position:0}))};render();}say(data.message);el.announcement.textContent=data.message;});socket.on('life-state',receive);socket.on('disconnect',()=>{el.connection.textContent='Connection lost. Trying to reconnect…'});
