'use strict';
const socket=io(),params=new URLSearchParams(location.search),gameId=params.get('game'),token=sessionStorage.getItem('loungeSessionToken'),playerId=(sessionStorage.getItem('loungeUsername')||'').trim().toLowerCase();
const el={connection:document.querySelector('#connection'),turn:document.querySelector('#turn'),map:document.querySelector('#map'),start:document.querySelector('#start'),director:document.querySelector('#director'),action:document.querySelector('#action'),move:document.querySelector('#move-status'),list:document.querySelector('#shopping-list'),players:document.querySelector('#players'),announcer:document.querySelector('#announcer'),urgent:document.querySelector('#urgent')};
let room=null,game=null,audio=null;
const accessibility = window.LoungeAccessibility?.createGameStateController({
  mode: 'GAME',
  statusEl: el.announcer,
  items: [
    { label: 'Press Electronic Mall Director', type: 'game' },
    { label: 'Swipe Or Use ATM', type: 'game' },
    { label: 'Read Shopping List', type: 'game' },
    { label: 'Read Position', type: 'game' },
    { label: 'Read Opponents', type: 'game' },
    { label: 'Help / Instructions', type: 'help' }
  ],
  hotkeys: { scores: [], players: ['p'], help: ['h', '?'] },
  helpText: 'Keyboard shortcuts: Arrow keys move. S presses the Electronic Mall Director. Enter swipes at stores or uses an ATM. L reads your shopping list. C reads your position. O reads opponents. Press P for connected players.'
});
function context(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audio||=new C();if(audio.state==='suspended')audio.resume().catch(()=>{});return audio}
function tone(notes,wave='sine',spacing=.08,volume=.1){const c=context();if(!c)return;const now=c.currentTime;notes.forEach((frequency,index)=>{const oscillator=c.createOscillator(),gain=c.createGain(),start=now+index*spacing;oscillator.type=wave;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(volume,start);gain.gain.exponentialRampToValueAtTime(.0001,start+.25);oscillator.connect(gain).connect(c.destination);oscillator.start(start);oscillator.stop(start+.26)})}
function sound(cue,message){if(!cue)return;if(cue.type==='swipe'||cue.type==='register')tone([1800,1100,500],'sawtooth',.045,.06);if(cue.type==='atm')tone([220,330,440,550],'square',.09,.07);if(cue.type==='register')setTimeout(()=>tone([900,1350,1800],'triangle',.055,.1),180);if(cue.type==='pa'){tone([784,1047],'sine',.18,.13);if('speechSynthesis'in window)setTimeout(()=>{speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(message))},500)}if(cue.type==='victory')tone([392,523,659,784,1047],'triangle',.1,.14);if(cue.type==='error')tone([120,85],'square',.12,.12)}
function say(message,urgent=false){const node=urgent?el.urgent:el.announcer;node.textContent='';requestAnimationFrame(()=>node.textContent=message)}function me(){return game?.players.find(player=>player.id===playerId)}function fail(message){sound({type:'error'});say(message,true)}
function syncAccessibilityState(){if(!accessibility||!game)return;accessibility.setPlayers((game.players||[]).map(player=>player.name));accessibility.setScores(Object.fromEntries((game.players||[]).map(player=>[player.name,`${player.remainingItems} items left, $${player.cash}`])))}
function render(){
  const mine=me(),current=MallMadnessEngine.space(mine?.position??0),myTurn=game?.turnPlayerId===playerId,playing=game?.status==='playing';
  el.connection.textContent=gameId?`Room ${gameId}. ${game?.status||'waiting'}.`:'Missing game. Return to the lounge.';el.turn.textContent=game?.announcement||'Waiting for shoppers.';el.start.hidden=room?.hostId!==playerId||playing;el.director.disabled=!playing||!myTurn||game.phase!=='director';el.action.disabled=!playing||!myTurn||!['moving','action'].includes(game.phase);el.move.textContent=myTurn?`${game.movesRemaining||0} movement spaces remain. ${game.sale?`Active sale: ${game.sale.category}, 50 percent off.`:'No active sale.'}`:`${game?.players?.find(player=>player.id===game.turnPlayerId)?.name||'Another shopper'} has the turn.`;
  el.map.replaceChildren(...MallMadnessEngine.MALL.map(space=>{const cell=document.createElement('div');cell.className=`space ${space.type}${mine?.position===space.id?' current':''}${game?.players?.some(player=>player.id!==playerId&&player.position===space.id)?' other':''}`;cell.role='gridcell';cell.setAttribute('aria-label',`${space.name}, row ${space.y+1}, column ${space.x+1}${mine?.position===space.id?', your current position':''}`);cell.textContent=space.type==='store'?`${space.name} ${space.item}, $${space.price}`:space.name;return cell}));
  const list=game?.myShoppingList||[];el.list.replaceChildren(...(list.length?list.map(item=>{const li=document.createElement('li');li.className=item.bought?'bought':'';li.textContent=`${item.item} at ${item.storeName}: ${item.bought?'bought':`needed, regular price $${item.price}`}`;return li}):[Object.assign(document.createElement('li'),{textContent:'Shopping list appears when the mall opens.'})]));el.players.replaceChildren(...(game?.players||[]).map(player=>Object.assign(document.createElement('li'),{textContent:`${player.name}: ${player.remainingItems} items remaining, $${player.cash}${player.id===game.turnPlayerId?', current turn':''}.`})));if(current)document.title=`${current.name} - Accessible Mall Madness Lounge`;
  syncAccessibilityState();
}
function pressDirector(){socket.emit('mall-director',{},result=>{if(!result.ok)fail(result.error)})}function move(direction){socket.emit('mall-move',{direction},result=>{if(!result.ok)fail(result.error)})}function action(){socket.emit('mall-action',{},result=>{if(!result.ok)fail(result.error)})}
function readList(){say((game?.myShoppingList||[]).map(item=>`${item.item} at ${item.storeName}: ${item.bought?'bought':'needed'}`).join('. ')||'Your shopping list is not ready.')}function readPosition(){const mine=me(),space=MallMadnessEngine.space(mine?.position),adjacent=MallMadnessEngine.nearbyStores(mine?.position);say(`${space?.name||'Unknown position'}. Cash $${mine?.cash??0}. Adjacent stores: ${adjacent.join(', ')||'none'}. ${game?.movesRemaining||0} moves remain.`)}function readOpponents(){say((game?.players||[]).filter(player=>player.id!==playerId).map(player=>`${player.name} needs ${player.remainingItems} items`).join('. ')||'No opponents are present.')}
el.start.addEventListener('click',()=>socket.emit('start-mall',{},result=>{if(!result.ok)fail(result.error)}));el.director.addEventListener('click',pressDirector);el.action.addEventListener('click',action);document.querySelector('#list-button').addEventListener('click',readList);document.querySelector('#position').addEventListener('click',readPosition);document.querySelector('#opponents').addEventListener('click',readOpponents);
document.addEventListener('keydown',event=>{if(event.target.matches('input,select,textarea'))return;if(accessibility?.handleKey(event))return;const key=event.key.toLowerCase();if(event.key==='Enter'&&game?.status==='waiting'&&room?.hostId===playerId&&!['BUTTON','A','INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName||'')){event.preventDefault();el.start.click();return}if(event.key.startsWith('Arrow')){event.preventDefault();move(event.key)}else if(key==='s'){event.preventDefault();pressDirector()}else if(key==='enter'){event.preventDefault();action()}else if(key==='l'){event.preventDefault();readList()}else if(key==='c'){event.preventDefault();readPosition()}else if(key==='o'){event.preventDefault();readOpponents()}});
function connect(){if(!token||!gameId)return fail('Missing login or game. Return to the lounge.');socket.emit('authenticate-token',{token},auth=>{if(!auth.ok)return fail(auth.error);socket.emit('join-game',{gameId},joined=>{if(!joined.ok)return fail(joined.error);room=joined.room;game=room.mall||null;render()})})}
socket.on('mall-state',payload=>{game=payload.game;if(game.status==='playing'){window.dispatchEvent(new CustomEvent('lounge-gameplay-started'));}sound(payload.cue,game.announcement);render();say(game.announcement)});socket.on('lobby-updated',updated=>{room=updated;playerId=playerId||room.players.find(p=>p.name===username)?.id||null;if(!game||game.status==='waiting'){game=room.mall||{status:'waiting',turnPlayerId:null,winnerId:null,announcement:'Waiting for the host to open the mall.',sequence:0,players:room.players.map(p=>({...p,position:0,cash:150,shoppingList:[],visitedATMs:new Set()})),phase:'director',movesRemaining:0,sale:null};render()}});socket.on('table-player-joined',data=>{if(!data?.message)return;if(game?.status==='waiting'){game=room.mall||{status:'waiting',turnPlayerId:null,winnerId:null,announcement:'Waiting for the host to open the mall.',sequence:0,players:room.players.map(p=>({...p,position:0,cash:150,shoppingList:[],visitedATMs:new Set()})),phase:'director',movesRemaining:0,sale:null};render();}say(data.message);el.announcement.textContent=data.message;window.LoungeAccessibility?.speak?.(data.message);});socket.on('connect',connect);socket.on('disconnect',()=>el.connection.textContent='Connection lost. Reconnecting...');window.addEventListener('pointerdown',context,{once:true});window.addEventListener('keydown',context,{once:true});render();
