'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
process.env.NODE_ENV='test';process.env.LOUNGE_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'uno-challenge-'));
const {io}=require('socket.io-client'),{startServer,server}=require('./server');
const call=(s,e,d={})=>new Promise(resolve=>s.emit(e,d,resolve));
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{const sockets=[];try{
 await startServer(0,'127.0.0.1');const url=`http://127.0.0.1:${server.address().port}`;
 async function user(name){const s=io(url,{transports:['websocket']});sockets.push(s);s.on('uno-state',p=>s.state=p.game);await new Promise(r=>s.on('connect',r));assert((await call(s,'register',{username:name,password:'TestRules9!'})).ok);return s;}
 const a=await user('WildPlayer'),b=await user('ChallengePlayer');
 async function setup(bot=false){for(let i=0;i<100;i++){await call(a,'leave-room');if(!bot)await call(b,'leave-room');const created=await call(a,'create-game',{category:'uno-classic'});assert(created.ok);if(bot)assert((await call(a,'add-computer-player')).ok);else assert((await call(b,'join-game',{gameId:created.room.code})).ok);assert((await call(a,'start-uno')).ok);await delay(20);const g=a.state,index=g.myHand.findIndex(c=>c.value==='Wild Draw 4'),color=g.discard.chosenColor||g.discard.color;if(index>=0&&g.turnPlayerId===g.players.find(p=>p.name==='WildPlayer').id&&g.myHand.some(c=>c.color===color))return index;}throw new Error('Could not deal test Draw Four');}
 for(const challenge of [true,false]){const index=await setup(),before=b.state.myHand.length;assert((await call(a,'uno-play',{indexes:[index],color:'Blue'})).ok);await delay(20);assert(a.state.pendingChallenge);assert.deepEqual(Object.keys(b.state.pendingChallenge).sort(),['offenderId','targetId']);assert.equal(JSON.stringify(b.state).includes('"illegal"'),false);assert.equal((await call(a,'uno-challenge',{challenge:true})).ok,false);assert.equal((await call(b,'uno-play',{indexes:[0],color:'Red'})).ok,false);const result=await call(b,'uno-challenge',{challenge});assert(result.ok,result.error);await delay(20);assert.equal(b.state.pendingChallenge,null);if(challenge){assert(Array.isArray(result.revealedHand));assert.equal(b.state.myHand.length,before);assert.equal(b.state.turnPlayerId,b.state.players.find(p=>p.name==='ChallengePlayer').id);}else{assert.equal(result.revealedHand,null);assert.equal(b.state.myHand.length,before+4);}assert.equal((await call(b,'uno-challenge',{challenge})).ok,false);}
 await call(b,'leave-room');const index=await setup(true);assert((await call(a,'uno-play',{indexes:[index],color:'Green'})).ok);for(let i=0;i<30&&a.state.pendingChallenge;i++)await delay(100);assert.equal(a.state.pendingChallenge,null,'Computer must accept Draw Four without stalling.');assert.match(a.state.announcement,/accepted four cards/);
 console.log('Live UNO challenge authorization, privacy, accept/challenge, and computer response passed.');
 }finally{sockets.forEach(s=>s.disconnect());server.close();setTimeout(()=>process.exit(process.exitCode||0),700)}})().catch(e=>{console.error(e);process.exitCode=1});
