'use strict';
const socket=io(),gameId=new URLSearchParams(location.search).get('game')||sessionStorage.getItem('loungeGameId'),token=sessionStorage.getItem('loungeSessionToken'),username=sessionStorage.getItem('loungeUsername');
const $=id=>document.getElementById(id),el={connection:$('connection'),announcement:$('announcement'),live:$('live'),start:$('start'),act:$('act'),uno:$('declare-uno'),dos:$('declare-dos'),centerReport:$('center-report'),handReport:$('hand-report'),scoreReport:$('score-report'),voice:$('voice'),wild:$('wild-color'),centerChoice:$('center-choice'),turn:$('turn-status'),center:$('center'),players:$('players'),hand:$('hand')};
let room=null,game=null,playerId=null,selected=0,marked=new Set(),lastSequence=0;
const accessibility = window.LoungeAccessibility?.createGameStateController({
	mode: 'GAME',
	statusEl: el.live,
	items: [
		{ label: 'Play Selected Or Draw', type: 'game' },
		{ label: 'Declare UNO', type: 'game' },
		{ label: 'Declare DOS', type: 'game' },
		{ label: 'Report Center', type: 'game' },
		{ label: 'Read Hand', type: 'game' },
		{ label: 'Opponent Tallies', type: 'game' },
		{ label: 'Help / Instructions', type: 'help' }
	],
	hotkeys: { scores: ['s'], players: ['p'], help: ['?'] },
	helpText: 'Keyboard shortcuts: Up or Down choose a card or Draw Card. Enter activates the selection. Wild cards open a color choice: Up or Down selects, Enter confirms, Escape cancels. Space draws in Uno; T reports the turn. In DOS, T changes the target and Space marks a pair. Space marks a DOS pair. C reports center cards. H reads your hand. S reads opponent tallies. U declares UNO. D declares DOS. P reads connected players.'
});
const symbols={Red:'●',Yellow:'▲',Green:'■',Blue:'◆',Pink:'♥',Teal:'⬟',Orange:'⬢',Purple:'✦',Wild:'★'};
function say(message){el.live.textContent='';requestAnimationFrame(()=>{el.live.textContent=message});if(el.voice.checked&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(message));}}
function accessibleUno(){return Boolean(window.LoungeAccessibility?.accessibleMode)}
function centerText(){return game.variant==='Uno Dos'?`Center row: left ${cardText(game.centerRow[0])}; right ${cardText(game.centerRow[1])}.`:`Showing ${cardText(game.discard)}${game.discard?.chosenColor?`, chosen color ${game.discard.chosenColor}`:''}.${game.variant==='Uno Flip!'?` ${game.side} side.`:''}`}
function cardText(card){return card?`${card.color} ${card.value}`:'Empty pile'}
function colorClass(color){return String(color||'wild').toLowerCase()}
function renderCard(card,className='center-card'){const item=document.createElement('div');item.className=`${className} ${colorClass(card?.color)}`;item.setAttribute('aria-label',cardText(card));item.innerHTML=`<span class="symbol" aria-hidden="true">${symbols[card?.color]||'★'}</span><span>${cardText(card)}</span>`;return item}
function render(){if(!game)return;document.body.dataset.side=game.side;if(accessibleUno()){const colors=game.side==='dark'?['Pink','Teal','Orange','Purple']:['Red','Yellow','Green','Blue'],previous=el.wild.value;el.wild.replaceChildren(...colors.map(color=>new Option(color,color)));el.wild.value=colors.includes(previous)?previous:colors[0];}el.announcement.textContent=game.announcement;el.start.hidden=game.status!=='waiting'||room?.hostId!==playerId;const myTurn=game.turnPlayerId===playerId;el.act.disabled=game.status!=='playing'||!myTurn;el.dos.hidden=game.variant!=='Uno Dos';el.centerChoice.hidden=game.variant!=='Uno Dos';el.turn.textContent=game.status==='finished'?`${game.players.find(p=>p.id===game.winnerId)?.name||'A player'} won.`:myTurn?`Your turn.${game.pendingDraw?` Pending draw stack: ${game.pendingDraw}.`:''}`:`Waiting for ${game.players.find(p=>p.id===game.turnPlayerId)?.name||'another player'}.`;el.center.replaceChildren(...(game.variant==='Uno Dos'?game.centerRow:[game.discard]).map(card=>renderCard(card)));el.players.replaceChildren(...game.players.map(p=>{const li=document.createElement('li');li.textContent=`${p.name}: ${p.cardCount} cards${p.eliminated?' (eliminated)':''}${p.id===game.turnPlayerId?' (turn)':''}${p.declaration?` (${p.declaration})`:''}`;return li}));if(selected>game.myHand.length||(!accessibleUno()&&selected>=game.myHand.length))selected=Math.max(0,game.myHand.length-1);el.hand.replaceChildren(...game.myHand.map((card,index)=>{const li=renderCard(card,'card');li.setAttribute('role','option');li.tabIndex=index===selected?0:-1;li.setAttribute('aria-selected',String(index===selected));if(marked.has(index))li.classList.add('marked');li.addEventListener('focus',()=>{selected=index;say(`Card ${index+1} of ${game.myHand.length}: ${cardText(card)}`)});li.addEventListener('click',()=>{selected=index;playOrDraw()});li.addEventListener('keydown',event=>{if(event.key!=='Enter')return;event.preventDefault();event.stopPropagation();selected=index;playOrDraw()});return li}));if(accessibleUno()&&game.status==='playing'){const item=document.createElement('li');item.textContent='Draw Card';item.setAttribute('role','option');item.setAttribute('aria-selected',String(selected===game.myHand.length));item.tabIndex=-1;item.addEventListener('click',()=>{selected=game.myHand.length;playOrDraw()});el.hand.append(item);}}
function syncAccessibilityState(){if(!accessibility||!game)return;accessibility.setPlayers((game.players||[]).map(player=>player.name));accessibility.setScores(Object.fromEntries((game.players||[]).map(player=>[player.name,`${player.cardCount} cards${player.eliminated?', eliminated':''}`])))}
function reportCenter(){if(game)say(centerText())}
function reportHand(){say(game.myHand.length?`Your hand has ${game.myHand.length} cards: ${game.myHand.map(cardText).join('; ')}.`:'Your hand is empty.')}
function reportScores(){say(game.players.filter(p=>p.id!==playerId).map(p=>`${p.name} has ${p.cardCount} cards${p.eliminated?', eliminated':''}`).join('. ')||'No opponents.')}
const wildDialog=document.createElement('dialog');
wildDialog.setAttribute('role','application');wildDialog.setAttribute('aria-label','Choose wild color');wildDialog.tabIndex=0;
const wildPrompt=document.createElement('p');wildDialog.append(wildPrompt);document.body.append(wildDialog);
let pendingWild=null,wildIndex=0;
function promptWild(indexes){pendingWild={indexes,sequence:game.sequence};wildIndex=0;wildDialog.showModal();wildDialog.focus();updateWildPrompt();}
function updateWildPrompt(){const colors=game.side==='dark'?UnoRules.DARK_COLORS:UnoRules.LIGHT_COLORS;wildPrompt.textContent=`Choose color: ${colors[wildIndex]}. Up or Down selects. Enter confirms. Escape cancels.`;say(wildPrompt.textContent);}
function sendPlay(indexes,color){socket.emit('uno-play',{indexes,color,centerIndex:Number(el.centerChoice.value)},result=>{if(!result.ok)say(result.error);else marked.clear();});}
wildDialog.addEventListener('cancel',event=>{event.preventDefault();pendingWild=null;wildDialog.close();});
wildDialog.addEventListener('close',()=>{pendingWild=null;window.focusLoungeGameplay?.();});
wildDialog.addEventListener('keydown',event=>{event.stopPropagation();if(event.altKey||event.ctrlKey||event.metaKey)return;const key=event.key.toLowerCase();if(['arrowup','arrowdown','enter','escape'].includes(key))event.preventDefault();if(key==='escape'){pendingWild=null;wildDialog.close();return;}if(['arrowup','arrowdown'].includes(key)){wildIndex=(wildIndex+(key==='arrowup'?-1:1)+4)%4;updateWildPrompt();return;}if(key==='enter'&&pendingWild){const choice=pendingWild,colors=game.side==='dark'?UnoRules.DARK_COLORS:UnoRules.LIGHT_COLORS;pendingWild=null;wildDialog.close();if(game.status==='playing'&&game.turnPlayerId===playerId&&game.sequence===choice.sequence)sendPlay(choice.indexes,colors[wildIndex]);else say('The turn changed. Choose your card again.');}});
const challengeDialog=document.createElement('dialog');challengeDialog.setAttribute('role','application');challengeDialog.setAttribute('aria-label','Wild Draw Four challenge');challengeDialog.tabIndex=0;
const challengeText=document.createElement('p'),challengeYes=document.createElement('button'),challengeNo=document.createElement('button');challengeText.textContent='Challenge Wild Draw Four? Y challenges. N accepts four cards and skips your turn. Up or Down selects, Enter confirms.';challengeYes.textContent='Challenge (Y)';challengeNo.textContent='Accept four cards (N)';challengeDialog.append(challengeText,challengeYes,challengeNo);document.body.append(challengeDialog);
let resolvingChallenge=false,challengeChoice=false;
function respondChallenge(challenge){if(resolvingChallenge)return;resolvingChallenge=true;socket.emit('uno-challenge',{challenge},result=>{resolvingChallenge=false;if(!result.ok)say(result.error);else if(result.revealedHand){const line=document.createElement('p');line.textContent=`Challenged hand: ${result.revealedHand.join('; ')||'empty'}.`;document.querySelector('.lounge-game-message-history')?.append(line);say(`${line.textContent} ${game.announcement}`);}});}
challengeYes.addEventListener('click',()=>respondChallenge(true));challengeNo.addEventListener('click',()=>respondChallenge(false));
challengeDialog.addEventListener('cancel',event=>event.preventDefault());challengeDialog.addEventListener('keydown',event=>{event.stopPropagation();if(event.altKey||event.ctrlKey||event.metaKey)return;const key=event.key.toLowerCase();if(key==='arrowup'||key==='arrowdown'){event.preventDefault();challengeChoice=!challengeChoice;say(challengeChoice?'Yes, challenge. Press Enter.':'No, accept four cards. Press Enter.');return;}if(key==='enter'&&event.target===challengeDialog){event.preventDefault();respondChallenge(challengeChoice);return;}if(key==='y'||key==='n'){event.preventDefault();respondChallenge(key==='y');}});challengeDialog.addEventListener('close',()=>window.focusLoungeGameplay?.());
function syncChallenge(){const active=game?.status==='playing'&&game.pendingChallenge?.targetId===playerId;if(active&&!challengeDialog.open){resolvingChallenge=false;challengeChoice=false;challengeDialog.showModal();challengeDialog.focus();}else if(!active&&challengeDialog.open)challengeDialog.close();}
function playOrDraw(){if(game?.pendingChallenge)return say('The next player must accept or challenge Draw Four.');if(pendingWild)return;if(!game||game.status!=='playing'||game.turnPlayerId!==playerId)return say('Wait for your turn.');if(!game.myHand.length||(accessibleUno()&&selected===game.myHand.length))return draw();const indexes=[...new Set(game.variant==='Uno Dos'&&marked.size?[...marked,selected]:[selected])],cards=indexes.map(index=>game.myHand[index]);let playable=false;if(game.variant==='Uno Dos'){const target=game.centerRow[Number(el.centerChoice.value)];playable=Boolean(target)&&[1,2].includes(cards.length)&&cards.every(card=>typeof card?.value==='number')&&cards.reduce((sum,card)=>sum+card.value,0)===target.value;}else{const chosen=cards[0],top=game.discard;const drawCard=String(chosen?.value).includes('Draw');playable=Boolean(chosen)&&((game.pendingDraw&&drawCard)||(!game.pendingDraw&&(chosen.color==='Wild'||chosen.color===(top?.chosenColor||top?.color)||chosen.value===top?.value)));}if(!playable){marked.clear();if(accessibleUno())return say('That card cannot be played. Choose another card or Draw Card.');return draw();}if(accessibleUno()&&cards[0]?.color==='Wild')return promptWild(indexes);sendPlay(indexes,el.wild.value);}
function draw(){socket.emit('uno-draw',{},result=>{if(!result.ok)say(result.error)})}
function declare(word){socket.emit('uno-declare',{word},result=>{if(!result.ok)say(result.error)})}
function connect(){if(!token||!gameId){el.connection.textContent='Missing login or room. Return to the lobby.';return}socket.emit('authenticate-token',{token},auth=>{if(!auth.ok){el.connection.textContent=auth.error;return}socket.emit('join-game',{gameId},result=>{if(!result.ok){el.connection.textContent=result.error;return}room=result.room;playerId=room.players.find(p=>p.name===username)?.id||room.players.find(p=>p.name===auth.username)?.id;game=room.uno||{variant:room.unoVariant,status:'waiting',side:'light',players:room.players.map(p=>({...p,cardCount:0})),myHand:[],centerRow:[],discard:null,announcement:`Waiting to start ${room.unoVariant}.`,sequence:0};el.connection.textContent=`Connected to room ${room.code}.`;render();syncChallenge()})})}
el.start.addEventListener('click',()=>socket.emit('start-uno',{},r=>{if(!r.ok)say(r.error)}));el.act.addEventListener('click',playOrDraw);el.uno.addEventListener('click',()=>declare('UNO'));el.dos.addEventListener('click',()=>declare('DOS'));el.centerReport.addEventListener('click',reportCenter);el.handReport.addEventListener('click',reportHand);el.scoreReport.addEventListener('click',reportScores);
el.hand.addEventListener('keydown',event=>{if(event.key!=='Enter')return;const card=event.target.closest('[role="option"]');if(!card||!el.hand.contains(card))return;event.preventDefault();event.stopImmediatePropagation();selected=[...el.hand.children].indexOf(card);playOrDraw()},true);
document.addEventListener('keydown',event=>{if(event.altKey||event.ctrlKey||event.metaKey||['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(accessibility?.handleKey(event))return;const key=event.key.toLowerCase();if(accessibleUno()&&game?.status==='playing'){if(['arrowup','arrowdown'].includes(key)){event.preventDefault();selected=(selected+(key==='arrowup'?-1:1)+game.myHand.length+1)%(game.myHand.length+1);render();window.focusLoungeGameplay?.();say(selected===game.myHand.length?'Draw Card. Press Enter to draw.':`Card ${selected+1} of ${game.myHand.length}: ${cardText(game.myHand[selected])}`);return}if(event.key===' '&&game.variant!=='Uno Dos'){event.preventDefault();draw();return}if(key==='t'&&game.variant!=='Uno Dos'){event.preventDefault();say(game.turnPlayerId===playerId?'Your turn.':`${game.players.find(p=>p.id===game.turnPlayerId)?.name||'Another player'}'s turn.`);return}if(key==='t'&&game.variant==='Uno Dos'){event.preventDefault();el.centerChoice.value=el.centerChoice.value==='0'?'1':'0';say(`DOS target: ${el.centerChoice.value==='0'?'left':'right'} pile.`);return}}if(game?.status==='finished')return;if(event.key==='Enter'&&game?.status==='waiting'&&room?.hostId===playerId&&!['BUTTON','A','INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName||'')){event.preventDefault();el.start.click();return}if(['arrowup','arrowdown'].includes(key)&&game?.myHand.length){event.preventDefault();selected=(selected+(key==='arrowup'?-1:1)+game.myHand.length)%game.myHand.length;render();el.hand.children[selected]?.focus();return}if(event.key===' '&&game?.variant==='Uno Dos'&&selected<game.myHand.length){event.preventDefault();marked.has(selected)?marked.delete(selected):marked.add(selected);render();say(marked.has(selected)?`${cardText(game.myHand[selected])} marked for a sum match.`:'Card unmarked.');return}if(event.key==='Enter'&&!['BUTTON','A'].includes(document.activeElement.tagName)){event.preventDefault();playOrDraw();return}if(key==='c')reportCenter();if(key==='h')reportHand();if(key==='s')reportScores();if(key==='u')declare('UNO');if(key==='d'&&game?.variant==='Uno Dos')declare('DOS')});
socket.on('connect',connect);socket.on('lobby-updated',updated=>{room=updated;playerId=playerId||room.players.find(p=>p.name===username)?.id||null;if(!game||game.status==='waiting'){game=room.uno||{variant:room.unoVariant,status:'waiting',side:'light',players:room.players.map(p=>({...p,cardCount:0})),myHand:[],centerRow:[],discard:null,announcement:`Waiting to start ${room.unoVariant}.`,sequence:0};render();syncAccessibilityState()}});socket.on('table-player-joined',data=>{if(!data?.message)return;if(game?.status==='waiting'){game=room.uno||{variant:room.unoVariant,status:'waiting',side:'light',players:room.players.map(p=>({...p,cardCount:0})),myHand:[],centerRow:[],discard:null,announcement:`Waiting to start ${room.unoVariant}.`,sequence:0};render();}say(data.message);el.announcement.textContent=data.message;window.LoungeAccessibility?.speak?.(data.message);});socket.on('uno-state',payload=>{const fresh=payload.game.sequence!==lastSequence;game=payload.game;if(game.status==='playing'){window.dispatchEvent(new CustomEvent('lounge-gameplay-started'));}lastSequence=game.sequence;if(payload.cue?.type==='card')window.playUnoCardSlide?.(payload.cue.pan);if(payload.cue?.type==='flip')window.playUnoFlip?.();if(payload.cue?.type==='warning'||payload.cue?.type==='declare')window.playUnoWarning?.();if(payload.cue?.type==='launcher')window.playUnoLauncher?.(payload.cue.amount);render();syncAccessibilityState();syncChallenge();if(fresh)say(accessibleUno()&&game.status==='playing'?`${game.announcement} ${game.pendingChallenge?.targetId===playerId?'Challenge Wild Draw Four? Y challenges. N accepts four cards.':''} ${centerText()} ${game.turnPlayerId===playerId?'Your turn.':`${game.players.find(p=>p.id===game.turnPlayerId)?.name||'Another player'}'s turn.`}`:game.announcement)});socket.on('disconnect',()=>{el.connection.textContent='Connection lost. Reconnecting…'});
