'use strict';
const socket=io("https://accessible-game-lounge.onrender.com"),gameId=new URLSearchParams(location.search).get('game')||sessionStorage.getItem('loungeGameId'),token=sessionStorage.getItem('loungeSessionToken'),username=sessionStorage.getItem('loungeUsername');
const $=id=>document.getElementById(id),el={connection:$('connection'),announcement:$('announcement'),live:$('live'),start:$('start'),act:$('act'),uno:$('declare-uno'),dos:$('declare-dos'),centerReport:$('center-report'),handReport:$('hand-report'),scoreReport:$('score-report'),voice:$('voice'),wild:$('wild-color'),centerChoice:$('center-choice'),turn:$('turn-status'),center:$('center'),players:$('players'),hand:$('hand')};
let room=null,game=null,playerId=null,selected=0,marked=new Set(),lastSequence=0;
const symbols={Red:'●',Yellow:'▲',Green:'■',Blue:'◆',Pink:'♥',Teal:'⬟',Orange:'⬢',Purple:'✦',Wild:'★'};
function say(message){el.live.textContent='';requestAnimationFrame(()=>{el.live.textContent=message});if(el.voice.checked&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(message));}}
function cardText(card){return card?`${card.color} ${card.value}`:'Empty pile'}
function colorClass(color){return String(color||'wild').toLowerCase()}
function renderCard(card,className='center-card'){const item=document.createElement('div');item.className=`${className} ${colorClass(card?.color)}`;item.setAttribute('aria-label',cardText(card));item.innerHTML=`<span class="symbol" aria-hidden="true">${symbols[card?.color]||'★'}</span><span>${cardText(card)}</span>`;return item}
function render(){if(!game)return;document.body.dataset.side=game.side;el.announcement.textContent=game.announcement;el.start.hidden=game.status!=='waiting'||room?.hostId!==playerId;const myTurn=game.turnPlayerId===playerId;el.act.disabled=game.status!=='playing'||!myTurn;el.dos.hidden=game.variant!=='Uno Dos';el.centerChoice.hidden=game.variant!=='Uno Dos';el.turn.textContent=game.status==='finished'?`${game.players.find(p=>p.id===game.winnerId)?.name||'A player'} won.`:myTurn?`Your turn.${game.pendingDraw?` Pending draw stack: ${game.pendingDraw}.`:''}`:`Waiting for ${game.players.find(p=>p.id===game.turnPlayerId)?.name||'another player'}.`;el.center.replaceChildren(...(game.variant==='Uno Dos'?game.centerRow:[game.discard]).map(card=>renderCard(card)));el.players.replaceChildren(...game.players.map(p=>{const li=document.createElement('li');li.textContent=`${p.name}: ${p.cardCount} cards${p.eliminated?' (eliminated)':''}${p.id===game.turnPlayerId?' (turn)':''}${p.declaration?` (${p.declaration})`:''}`;return li}));if(selected>=game.myHand.length)selected=Math.max(0,game.myHand.length-1);el.hand.replaceChildren(...game.myHand.map((card,index)=>{const li=renderCard(card,'card');li.setAttribute('role','option');li.tabIndex=index===selected?0:-1;li.setAttribute('aria-selected',String(index===selected));if(marked.has(index))li.classList.add('marked');li.addEventListener('focus',()=>{selected=index;say(`Card ${index+1} of ${game.myHand.length}: ${cardText(card)}`)});li.addEventListener('click',()=>{selected=index;playOrDraw()});return li}));}
function reportCenter(){say(game.variant==='Uno Dos'?`Center Row: left ${cardText(game.centerRow[0])}; right ${cardText(game.centerRow[1])}.`:`Active discard: ${cardText(game.discard)}.${game.variant==='Uno Flip!'?` ${game.side} side.`:''}`)}
function reportHand(){say(game.myHand.length?`Your hand has ${game.myHand.length} cards: ${game.myHand.map(cardText).join('; ')}.`:'Your hand is empty.')}
function reportScores(){say(game.players.filter(p=>p.id!==playerId).map(p=>`${p.name} has ${p.cardCount} cards${p.eliminated?', eliminated':''}`).join('. ')||'No opponents.')}
function playOrDraw(){if(!game||game.turnPlayerId!==playerId)return say('Wait for your turn.');if(!game.myHand.length)return draw();const indexes=[...new Set(game.variant==='Uno Dos'&&marked.size?[...marked,selected]:[selected])],cards=indexes.map(index=>game.myHand[index]);let playable=false;if(game.variant==='Uno Dos'){const target=game.centerRow[Number(el.centerChoice.value)];playable=Boolean(target)&&[1,2].includes(cards.length)&&cards.every(card=>typeof card?.value==='number')&&cards.reduce((sum,card)=>sum+card.value,0)===target.value;}else{const chosen=cards[0],top=game.discard;const drawCard=String(chosen?.value).includes('Draw');playable=Boolean(chosen)&&((game.pendingDraw&&drawCard)||(!game.pendingDraw&&(chosen.color==='Wild'||chosen.color===(top?.chosenColor||top?.color)||chosen.value===top?.value)));}if(!playable){marked.clear();return draw();}socket.emit('uno-play',{indexes,color:el.wild.value,centerIndex:Number(el.centerChoice.value)},result=>{if(!result.ok)say(result.error);else marked.clear();});}
function draw(){socket.emit('uno-draw',{},result=>{if(!result.ok)say(result.error)})}
function declare(word){socket.emit('uno-declare',{word},result=>{if(!result.ok)say(result.error)})}
function connect(){if(!token||!gameId){el.connection.textContent='Missing login or room. Return to the lobby.';return}socket.emit('authenticate-token',{token},auth=>{if(!auth.ok){el.connection.textContent=auth.error;return}socket.emit('join-game',{gameId},result=>{if(!result.ok){el.connection.textContent=result.error;return}room=result.room;playerId=room.players.find(p=>p.name===username)?.id||room.players.find(p=>p.name===auth.username)?.id;game=room.uno||{variant:room.unoVariant,status:'waiting',side:'light',players:room.players.map(p=>({...p,cardCount:0})),myHand:[],centerRow:[],discard:null,announcement:`Waiting to start ${room.unoVariant}.`,sequence:0};el.connection.textContent=`Connected to room ${room.code}.`;render()})})}
el.start.addEventListener('click',()=>socket.emit('start-uno',{},r=>{if(!r.ok)say(r.error)}));el.act.addEventListener('click',playOrDraw);el.uno.addEventListener('click',()=>declare('UNO'));el.dos.addEventListener('click',()=>declare('DOS'));el.centerReport.addEventListener('click',reportCenter);el.handReport.addEventListener('click',reportHand);el.scoreReport.addEventListener('click',reportScores);
document.addEventListener('keydown',event=>{if(event.altKey||event.ctrlKey||event.metaKey||['INPUT','SELECT'].includes(document.activeElement.tagName))return;const key=event.key.toLowerCase();if(['arrowup','arrowdown'].includes(key)&&game?.myHand.length){event.preventDefault();selected=(selected+(key==='arrowup'?-1:1)+game.myHand.length)%game.myHand.length;render();el.hand.children[selected]?.focus();return}if(event.key===' '&&game?.variant==='Uno Dos'){event.preventDefault();marked.has(selected)?marked.delete(selected):marked.add(selected);render();say(marked.has(selected)?`${cardText(game.myHand[selected])} marked for a sum match.`:'Card unmarked.');return}if(event.key==='Enter'&&!['BUTTON','A'].includes(document.activeElement.tagName)){event.preventDefault();playOrDraw();return}if(key==='c')reportCenter();if(key==='h')reportHand();if(key==='s')reportScores();if(key==='u')declare('UNO');if(key==='d'&&game?.variant==='Uno Dos')declare('DOS')});
socket.on('connect',connect);socket.on('lobby-updated',updated=>{room=updated});socket.on('uno-state',payload=>{const fresh=payload.game.sequence!==lastSequence;game=payload.game;lastSequence=game.sequence;if(payload.cue?.type==='card')window.playUnoCardSlide?.(payload.cue.pan);if(payload.cue?.type==='flip')window.playUnoFlip?.();if(payload.cue?.type==='warning'||payload.cue?.type==='declare')window.playUnoWarning?.();if(payload.cue?.type==='launcher')window.playUnoLauncher?.(payload.cue.amount);render();if(fresh)say(game.announcement)});socket.on('disconnect',()=>{el.connection.textContent='Connection lost. Reconnecting…'});
